import {ART_COLORS,ART_STAMPS} from './art-postcard.js?v=20261007-frame';
export const FRAME_MILESTONE={level:18,label:'🖼️ 나의 엽서 배경과 액자',activity:'art-frame',description:'내 그림에 배경과 액자를 고르고 작은 장식을 놓아요.'};
export const FRAME_BACKGROUNDS={cream:'따뜻한 종이',meadow:'초록 정원',night:'별빛 저녁',sunset:'살구 노을'};
export const FRAME_BORDERS={wood:'나무 액자',leaf:'잎사귀 액자',star:'별빛 액자'};
export const FRAME_ORNAMENTS={leaf:'🌿',flower:'🌼',star:'⭐',none:'지우기'};
const slots={'top-left':'왼쪽 위','top-right':'오른쪽 위','bottom-right':'오른쪽 아래'};
const valid=d=>Object.hasOwn(FRAME_BACKGROUNDS,d?.background)&&Object.hasOwn(FRAME_BORDERS,d?.frame)&&Object.hasOwn(FRAME_ORNAMENTS,d?.ornament)&&Object.hasOwn(slots,d?.placement);
export function installArtFrame(c){
 const {dialog,open,esc,button}=c,doc=dialog.ownerDocument;let owner=null,token=null,style=null,selected='leaf',dirty=false,drag=null,generation=0;
 const state=()=>c.getJournal()?.art;
 const earned=()=>!!state()?.decorated_at;
 const label=lv=>earned()?'✓ 나의 작은 액자 · 다시 꾸미기':lv<18?'🔒 Lv.18에 열려요':state()?.phase!==2?'그림 엽서부터 완성해요':'내 그림에 액자 고르기';
 const key=()=> 'art-frame-draft:v1:'+owner;
 function persist(){if(!dirty||owner!==c.getStudent().id||token!==c.getToken())return;try{localStorage.setItem(key(),JSON.stringify({v:1,...style}))}catch{status('임시저장하지 못했어요. 액자 저장 버튼으로 수첩에 남겨 주세요.')}}
 function status(text){const el=doc.getElementById('frameStatus');if(el)el.textContent=text}
 function start(){generation++;persist();owner=c.getStudent().id;token=c.getToken();dirty=false;drag=null;
  if(state()?.phase!==2){open('그림 엽서를 먼저 완성해요','내 그림이 액자의 주인공이에요.','<div class="sa-stamp"><h3>아직 액자에 담을 그림이 없어요.</h3><p>물감을 섞고 나만의 그림 엽서를 저장해 주세요.</p><button class="sa-button primary" data-workshop="art-postcard">그림 엽서 만들러 가기</button></div>');return}
  style={background:state().background||'cream',frame:state().frame||'wood',ornament:state().ornament||'leaf',placement:state().placement||'bottom-right'};
  try{const draft=JSON.parse(localStorage.getItem(key())||'null');if(draft?.v===1&&valid(draft)){style={background:draft.background,frame:draft.frame,ornament:draft.ornament,placement:draft.placement};dirty=true}}catch{}
  selected=style.ornament;view();if(dirty)status('이 기기에서 꾸미던 액자를 다시 펼쳤어요.');
 }
 function view(){
  const picks=(group,list)=>Object.entries(list).map(([id,text])=>'<button data-frame-'+group+'="'+id+'" aria-pressed="'+(style[group]===id)+'">'+esc(text)+'</button>').join('');
  open('🖼️ 나의 작은 액자 공방','그림은 그대로, 어울리는 풍경을 골라요.','<p class="frame-intro">배경과 액자를 골라 보세요. 작은 장식을 고른 뒤 액자 모서리를 누르거나 끌어 놓을 수 있어요.</p><div class="frame-workshop"><div><div id="framePreview" class="frame-preview" role="group" aria-label="내 그림 액자 미리보기"><span class="frame-landscape" aria-hidden="true"></span><div class="frame-picture"><div class="art-mini-grid" role="img" aria-label="내가 저장한 그림 엽서">'+state().cells.map(id=>'<i style="background:'+ART_COLORS[id].hex+'"></i>').join('')+'</div><span class="frame-postmark" aria-hidden="true">'+ART_STAMPS[state().stamp]+'</span></div>'+Object.entries(slots).map(([id,name])=>'<button class="frame-slot" data-frame-slot="'+id+'" aria-label="'+name+'에 선택한 장식 놓기"></button>').join('')+'</div><p class="frame-caption">내가 만든 그림, 내가 고른 자리</p></div><aside class="frame-tools"><h3>배경의 분위기</h3><div class="frame-picks">'+picks('background',FRAME_BACKGROUNDS)+'</div><h3>그림을 감싸는 액자</h3><div class="frame-picks">'+picks('frame',FRAME_BORDERS)+'</div><h3>모서리에 놓을 작은 장식</h3><div class="frame-picks frame-stickers">'+Object.entries(FRAME_ORNAMENTS).map(([id,text])=>'<button data-frame-ornament="'+id+'" aria-pressed="'+(selected===id)+'" aria-label="'+({leaf:'잎',flower:'꽃',star:'별',none:'장식 지우기'}[id])+' 선택">'+text+'</button>').join('')+'</div><button class="sa-button" data-frame-reset>저장된 모습으로 되돌리기</button></aside></div><p id="frameStatus" class="sa-note" role="status" aria-live="polite">배경과 액자를 바꿔도 원래 그림은 유지돼요.</p><button class="sa-button primary" data-frame-save>내 액자 수첩에 저장하기</button><div id="frameFeedback" class="sa-feedback" role="status" aria-live="polite"></div><p>'+button('map','← 탐험 수첩')+'</p>');preview();
 }
 function preview(){const el=doc.getElementById('framePreview');if(!el)return;dialog.querySelectorAll('[data-frame-ornament]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.frameOrnament===selected)));el.dataset.background=style.background;el.dataset.frame=style.frame;el.querySelectorAll('[data-frame-slot]').forEach(b=>{const placed=style.ornament!=='none'&&b.dataset.frameSlot===style.placement;b.textContent=placed?FRAME_ORNAMENTS[style.ornament]:'＋';b.setAttribute('aria-label',slots[b.dataset.frameSlot]+(placed?' · '+({leaf:'잎',flower:'꽃',star:'별'}[style.ornament])+' 장식':' · 선택한 장식 놓기'));b.setAttribute('aria-pressed',String(placed))});for(const group of ['background','frame'])dialog.querySelectorAll('[data-frame-'+group+']').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset['frame'+group[0].toUpperCase()+group.slice(1)]===style[group])))}
 function change(){dirty=true;preview();status('미리보기예요. 마음에 들면 액자를 저장해 주세요.');persist()}
 function place(id){if(!Object.hasOwn(slots,id)||!owned()||c.getSaving())return;style.ornament=selected;style.placement=id;change()}
 function owned(){return owner===c.getStudent().id&&token===c.getToken()}
 async function save(){if(c.getSaving()||!owned())return;persist();const snapshot={...style},who=owner,pin=token,request=generation,feedback=doc.getElementById('frameFeedback'),buttons=[...dialog.querySelectorAll('button')].map(b=>[b,b.disabled]);c.setSaving(true);buttons.forEach(([b])=>b.disabled=true);feedback.textContent='내 그림 액자를 수첩에 담고 있어요…';
  try{const {data,error}=await c.db.rpc('student_art_frame',{p_token:pin,p_background:snapshot.background,p_frame:snapshot.frame,p_ornament:snapshot.ornament,p_placement:snapshot.placement});if(error||!data||!data.decorated_at||!valid(data)||Object.keys(snapshot).some(k=>data[k]!==snapshot[k]))throw error||Error('Unconfirmed frame');if(request!==generation||who!==c.getStudent().id||pin!==c.getToken())return;c.getJournal().art=data;c.markLoaded();c.render();dirty=false;try{localStorage.removeItem(key())}catch{}feedback.innerHTML='<b>✓ 나의 작은 액자를 저장했어요.</b><p>다시 펼쳐 다른 분위기로 꾸며도 괜찮아요.</p>';status('수첩에 저장한 액자예요. 다른 기기에서도 펼칠 수 있어요.');}
  catch{if(request===generation&&owned())feedback.textContent='저장을 확인하지 못했어요. 꾸민 모습은 그대로예요. 연결을 확인하고 다시 눌러 주세요.'}
  finally{c.setSaving(false);buttons.forEach(([b,disabled])=>{if(b.isConnected)b.disabled=disabled})}
 }
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||!Object.keys(b.dataset).some(k=>k.startsWith('frame'))||c.getSaving())return;if(!owned()){dirty=false;open('새 계정의 수첩을 펼쳐 주세요','계정이 바뀌었어요.',button('map','탐험 수첩'));return}for(const group of ['background','frame']){const value=b.dataset['frame'+group[0].toUpperCase()+group.slice(1)];if(value&&Object.hasOwn(group==='background'?FRAME_BACKGROUNDS:FRAME_BORDERS,value)){style[group]=value;change();return}}if(b.dataset.frameOrnament&&Object.hasOwn(FRAME_ORNAMENTS,b.dataset.frameOrnament)){selected=b.dataset.frameOrnament;dialog.querySelectorAll('[data-frame-ornament]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));status('놓을 모서리를 눌러 주세요.');return}if(b.dataset.frameSlot){place(b.dataset.frameSlot);return}if(b.hasAttribute('data-frame-reset')){try{localStorage.removeItem(key())}catch{}dirty=false;start();return}if(b.hasAttribute('data-frame-save'))save()});
 dialog.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-frame-ornament]');if(!b||e.button!==0||!e.isPrimary||c.getSaving()||!owned())return;selected=b.dataset.frameOrnament;drag={id:e.pointerId,x:e.clientX,y:e.clientY,b};b.setPointerCapture(e.pointerId)});
 dialog.addEventListener('pointermove',e=>{if(drag?.id!==e.pointerId||!owned())return;const target=doc.elementFromPoint(e.clientX,e.clientY)?.closest('[data-frame-slot]');dialog.querySelectorAll('[data-frame-slot]').forEach(b=>b.classList.toggle('drop-ready',b===target))});
 for(const event of ['pointerup','pointercancel','lostpointercapture'])dialog.addEventListener(event,e=>{if(drag?.id!==e.pointerId)return;const held=drag;drag=null;const target=doc.elementFromPoint(e.clientX,e.clientY)?.closest('[data-frame-slot]');if(event==='pointerup'&&target&&Math.hypot(e.clientX-held.x,e.clientY-held.y)>8)place(target.dataset.frameSlot);dialog.querySelectorAll('[data-frame-slot]').forEach(b=>b.classList.remove('drop-ready'));if(held.b.hasPointerCapture(e.pointerId))held.b.releasePointerCapture(e.pointerId)});
 dialog.addEventListener('close',()=>{drag=null;persist()});doc.defaultView.addEventListener('pagehide',persist);
 doc.addEventListener('student-dashboard-updated',()=>{if(owner!==null&&!owned()){generation++;dirty=false;drag=null;if(doc.getElementById('framePreview'))dialog.close()}});
 return {start,label,earned};
}
