export const CHAPTER_ONE_LOCATIONS=['classroom','hallway','library','garden','playground','pond','cafeteria'];
export const CHAPTER_PROMISES=[
 {id:'kindness',icon:'🤝',title:'친구의 말을 끝까지 듣기',description:'내 차례를 기다리며 친구가 어떤 마음인지 생각해 볼래요.'},
 {id:'reading',icon:'📖',title:'책에서 만난 생각 나누기',description:'기억에 남는 장면과 내 생각을 친구에게 들려줄래요.'},
 {id:'observation',icon:'🌱',title:'우리 주변의 변화 살펴보기',description:'학교의 식물이나 물건을 자세히 보고 새로 발견한 것을 말할래요.'}
];
export const CHAPTER_ONE_MILESTONE={level:10,label:'🏵️ 첫 모험 기념식 · 학교 탐험가 휘장',activity:'chapter-one',description:'일곱 탐험 도장과 정원 관찰을 모아, 나의 첫 모험을 완성해요.'};
export function mementoArt(){
 return '<svg class="sa-memento-art" viewBox="0 0 240 220" role="img" aria-label="학교와 책, 일곱 별이 새겨진 초록빛 학교 탐험가 휘장"><path d="M64 151L52 213L87 198L108 219L120 162M176 151L188 213L153 198L132 219L120 162" fill="#558671" stroke="#38654f" stroke-width="4"/><path d="M86 177L81 204M154 177L159 204" stroke="#b7d2a9" stroke-width="5"/><circle cx="120" cy="98" r="88" fill="#eccc82" stroke="#b18f4d" stroke-width="4"/><circle cx="120" cy="98" r="76" fill="#fcf4d9" stroke="#c5a86c" stroke-width="2"/>'+Array.from({length:7},(_,i)=>{const a=(i*360/7-90)*Math.PI/180,x=120+62*Math.cos(a),y=98+62*Math.sin(a);return '<path d="M0-6L2-2L6 0L2 2L0 6L-2 2L-6 0L-2-2Z" transform="translate('+x+' '+y+')" fill="#ab8e4c"/>'}).join('')+'<path d="M84 116V77L120 52L156 77V116Z" fill="#97bcb1" stroke="#4a7465" stroke-width="3"/><path d="M80 78L120 49L160 78" fill="none" stroke="#4a7465" stroke-width="6" stroke-linecap="round"/><rect x="110" y="70" width="20" height="21" rx="3" fill="#fff9e5"/><path d="M120 74V85H127" fill="none" stroke="#6b8b6e" stroke-width="2"/><path d="M75 103Q99 96 120 109Q141 96 165 103V133Q141 126 120 140Q99 126 75 133Z" fill="#fffdf0" stroke="#756d47" stroke-width="3"/><path d="M120 110V138M86 111L108 113M132 113L154 111M86 120L108 122M132 122L154 120" fill="none" stroke="#c8b984" stroke-width="3"/></svg>';
}
export function chapterOneView({chapters,completed,workshop,nickname,promise},esc){
 chapters=chapters.filter(c=>CHAPTER_ONE_LOCATIONS.includes(c.id));
 const done=!!workshop?.chapter_one_complete,stamps=chapters.filter(c=>c.steps.every(s=>completed.has(s.id))).length,ready=stamps===7&&workshop?.garden_complete;
 return '<div class="sa-chapter-ceremony '+(done?'earned':'')+'"><span class="sa-eyebrow">모험학교 · 첫 번째 장</span>'+mementoArt()+'<h3>'+(done?esc(nickname)+'의 첫 모험이 완성됐어요!':'작은 배움이 모여, 학교 탐험가!')+'</h3><p>교실에서 준비하고, 복도에서 배려하고,<br>책과 자연에서 새로운 것을 발견했어요.<br>모험은 이제 진짜 학교에서도 이어져요.</p>'+(done?'<strong class="sa-memento-earned">✓ 학교 탐험가 휘장을 받았어요</strong>':'<strong>탐험 도장 '+stamps+' / 7개 · '+(workshop?.garden_complete?'정원 관찰 완료':'정원 관찰을 기다려요')+'</strong>')+'</div>'+
  (!done?'<h3>기념식까지 남은 발자국</h3><div class="sa-ceremony-checklist">'+chapters.map(c=>{const finished=c.steps.every(s=>completed.has(s.id));return '<button class="sa-destination" data-chapter="'+c.id+'"><b>'+c.icon+' '+c.name+'</b><small>'+(finished?'✓ 탐험 도장 획득':'남은 이야기 이어가기 →')+'</small></button>'}).join('')+'<button class="sa-destination" data-workshop="garden"><b>🌿 정원 변화 찾기</b><small>'+(workshop?.garden_complete?'✓ 관찰 완료':'관찰하러 가기 →')+'</small></button></div>':'')+
  '<h3>내가 이어 갈 작은 약속</h3><p class="sa-note">앞으로 해 보고 싶은 것을 골라요. 나중에 바꿔도 괜찮아요.</p><div class="sa-promises">'+CHAPTER_PROMISES.map(p=>'<button class="sa-promise" data-promise="'+p.id+'" aria-pressed="'+(promise===p.id)+'"><span aria-hidden="true">'+p.icon+'</span><div><b>'+p.title+'</b><p>'+p.description+'</p></div></button>').join('')+'</div><div id="saChapterFeedback" class="sa-feedback" role="status" aria-live="polite"></div><div class="sa-chapter-footer"><button class="sa-button primary" data-sa="finish-chapter" '+(!done&&!ready?'disabled':'')+'>'+(done?'내 약속 저장하기':'학교 탐험가 휘장 받기')+'</button>'+(done?'<button class="sa-button" data-chapter-badge="'+(workshop.chapter_one_badge===false?'true':'false')+'">'+(workshop.chapter_one_badge===false?'휘장 다시 달기':'휘장 잠시 보관하기')+'</button>':'')+'</div><p class="sa-note">휘장은 내 소개에 다는 기념 장식이에요. 골드를 쓰지 않고, 경험치나 능력치도 바뀌지 않아요. Lv.10의 50 골드 선물은 기존 레벨 선물로 한 번 받아요.</p>';
}
export function profileMemento(workshop){return workshop?.chapter_one_complete&&workshop.chapter_one_badge!==false?'<button class="sa-profile-memento" data-workshop="chapter-one" aria-label="학교 탐험가 휘장과 나의 약속 보기">'+mementoArt()+'<span>학교 탐험가<br><small>첫 모험의 소중한 기억</small></span></button>':''}
