export const FINALE_MILESTONE={level:20,label:'🎏 우리들의 기억 가랜드',activity:'school-finale',description:'끝낸 이야기 세 가지를 골라 가랜드에 걸어요. 함께 자란 모험가 리본이 남아요.'};
const MEMORIES={melody:{icon:'🎵',name:'환영 멜로디',text:'루미와 흩어진 악보를 이었어요.',activity:'music-sequence'},kindness:{icon:'🤝',name:'나루와의 길',text:'나루가 원하는 도움을 물어봤어요.',activity:'kindness-chapter'},parcel:{icon:'📦',name:'책 나눔 배달',text:'표식을 따라 토리의 꾸러미를 찾았어요.',activity:'parcel-adventure'},art:{icon:'🎨',name:'나만의 그림',text:'직접 그린 엽서에 액자를 꾸몄어요.',activity:'art-frame'},letter:{icon:'🌿',name:'초록 편지',text:'새싹을 살펴 토리에게 편지를 전했어요.',activity:'garden-letter'}};
const RIBBONS={meadow:'초록 숲',sunset:'살구 노을',sky:'맑은 하늘'};
const empty=()=>({earned:[],memories:[],ribbon:'meadow',wearing:false,completed_at:null});
const known=id=>Object.hasOwn(MEMORIES,id),validSlots=a=>Array.isArray(a)&&a.length===3&&a.every(x=>x===null||known(x))&&new Set(a.filter(Boolean)).size===a.filter(Boolean).length;
const validState=s=>s&&Array.isArray(s.earned)&&s.earned.every(known)&&Array.isArray(s.memories)&&Object.hasOwn(RIBBONS,s.ribbon)&&typeof s.wearing==='boolean'&&(s.completed_at?validSlots(s.memories)&&s.memories.every(Boolean):s.memories.length===0);
export function installSchoolFinale(c){
 const doc=document,d=doc.createElement('dialog');d.id='schoolFinaleDialog';d.className='parcel-dialog finale-dialog';d.setAttribute('aria-labelledby','finaleTitle');doc.body.append(d);
 const decoration=doc.createElement('div');decoration.className='finale-world';decoration.setAttribute('aria-hidden','true');doc.querySelector('#classroomHub .hub-stage')?.append(decoration);
 let owner=null,token=null,state=empty(),loaded=false,task=null,epoch=0,readVersion=0,view=0,busy=false,slots=[null,null,null],ribbon='meadow',selected=null,dirty=false,drag=null,ignoreClick=false,opener=null;
 const owned=()=>owner===c.getStudent()?.id&&token===c.getToken(),completed=()=>owned()&&loaded&&!!state.completed_at;
 const draftKey=()=> 'school-finale-draft:v1:'+owner;
 const flags=(values,interactive=false)=>'<div class="finale-cord" data-ribbon="'+ribbon+'">'+values.map((id,i)=>interactive?'<button class="finale-flag" data-final-slot="'+i+'" aria-label="'+(i+1)+'번째 자리 · '+(id?MEMORIES[id].name:'선택한 기억 걸기')+'"><span>'+ (id?MEMORIES[id].icon:'＋')+'</span><b>'+(id?MEMORIES[id].name:(i+1)+'번째 자리')+'</b></button>':'<span class="finale-flag"><span>'+MEMORIES[id].icon+'</span><b>'+MEMORIES[id].name+'</b></span>').join('')+'</div>';
 function updateWorld(){decoration.hidden=!completed();if(completed()){decoration.dataset.ribbon=state.ribbon;decoration.innerHTML=state.memories.map(id=>'<i>'+MEMORIES[id].icon+'</i>').join('')}else decoration.replaceChildren();c.onChange?.()}
 function reset(){epoch++;readVersion++;view++;owner=c.getStudent()?.id;token=c.getToken();state=empty();loaded=false;task=null;busy=false;dirty=false;selected=null;drag=null;slots=[null,null,null];if(d.open)d.close();doc.getElementById('campusNpcDialog')?.close();updateWorld()}
 async function load(force=false){if(!owned())reset();if(loaded&&!force)return true;if(task&&!force)return task;if(!owner||!token)return false;const id=owner,t=token,g=epoch,v=++readVersion;let pending;pending=(async()=>{try{const {data,error}=await c.db.rpc('student_school_finale',{p_token:t,p_action:'read'});if(error||!validState(data))throw error||Error('Invalid finale');if(g!==epoch||v!==readVersion||id!==c.getStudent()?.id||t!==c.getToken())return false;state=data;loaded=true;updateWorld();return true}catch{if(g===epoch&&v===readVersion){loaded=false;updateWorld()}return false}finally{if(task===pending)task=null}})();task=pending;return pending}
 function open(subtitle,html){if(!d.open)opener=doc.activeElement;d.innerHTML='<header><div><span>두 번째 모험 이야기 · Lv.20</span><h2 id="finaleTitle">우리들의 기억 가랜드</h2><p>'+subtitle+'</p></div><button data-final="close" autofocus>닫기</button></header><div class="parcel-body">'+html+'</div>';if(!d.open)d.showModal();d.scrollTop=0}
 const teacher=text=>'<div class="finale-teacher"><img src="maps/npcs/teacher-v1.webp" alt="담임선생님"><p>'+text+'</p></div>';
 const feedback=()=>'<p id="finaleStatus" role="status" aria-live="polite"></p>';
 function status(text){const el=doc.getElementById('finaleStatus');if(el)el.textContent=text}
 async function start(){if(busy)return;if(!owned())reset();const requested=++view;open('수첩에 남긴 기억을 꺼내고 있어요.','<p>함께했던 이야기를 확인하고 있어요…</p>');if(!await load(true)){if(requested===view&&d.open)open('잠깐, 연결을 확인해 주세요.','<button data-final="retry">기억 다시 읽기</button>');return}if(requested!==view||!d.open)return;
  if(c.levelInfo(c.getStudent()?.xp||0).level<20&&!completed()){open('Lv.20에 함께 이야기의 끝을 꾸며요.',teacher('“네가 학교에서 남긴 작은 기억들이 모이고 있구나. 조금 더 자라면 마음에 남는 세 가지를 걸어 보자.”'));return}
  if(completed()){finish();return}begin();
 }
 function begin(){slots=state.memories.length===3?[...state.memories]:[null,null,null];ribbon=state.ribbon;dirty=false;selected=null;
  try{const draft=JSON.parse(localStorage.getItem(draftKey())||'null');if(draft?.v===1&&validSlots(draft.slots)&&draft.slots.every(x=>!x||state.earned.includes(x))&&Object.hasOwn(RIBBONS,draft.ribbon)){slots=draft.slots;ribbon=draft.ribbon;dirty=true}}catch{}
  workshop();if(dirty)status('이 기기에서 꾸미던 기억을 다시 꺼냈어요.');
 }
 function workshop(){open('기억 세 가지를 골라 줄에 걸어 보세요.',teacher('“도움을 주고, 발견하고, 네 생각을 표현했구나! 가장 마음에 남는 세 가지를 원하는 순서로 걸어 볼까?”')+'<div id="finaleBoard" class="finale-board">'+flags(slots,true)+'</div><p class="finale-help">기억 조각을 끌어 놓거나, 조각과 자리를 차례로 눌러요. 걸어 둔 자리를 다시 누르면 내려놓아요.</p><div class="finale-memories">'+Object.entries(MEMORIES).map(([id,m])=>state.earned.includes(id)?'<button data-final-memory="'+id+'" aria-pressed="false"><span>'+m.icon+'</span><b>'+m.name+'</b><small>'+m.text+'</small></button>':'<div class="finale-missing"><span>'+m.icon+'</span><b>'+m.name+'</b><small>아직 수첩에 없는 기억이에요.</small><button data-final-visit="'+id+'">이야기 만나러 가기</button></div>').join('')+'</div><p class="parcel-note">완성한 기억 '+state.earned.length+' / 5 · 서로 다른 기억 세 개로 꾸며요. 모든 이야기를 끝낼 필요는 없어요.</p><div class="finale-ribbons" role="group" aria-label="기념 리본 색">'+Object.entries(RIBBONS).map(([id,name])=>'<button data-final-ribbon="'+id+'" aria-pressed="'+(ribbon===id)+'">'+name+'</button>').join('')+'</div><p class="parcel-note">키보드: 기억 선택 → Tab으로 자리 이동 → Enter. 접속하지 않은 날에도 기억은 사라지지 않아요.</p><button data-final="clear">줄에서 모두 내려놓기</button> <button class="parcel-primary" data-final="save">이 모습으로 이야기 마무리하기</button>'+feedback());preview()}
 function preview(){const board=doc.getElementById('finaleBoard');if(!board)return;board.querySelector('.finale-cord').dataset.ribbon=ribbon;board.querySelectorAll('[data-final-slot]').forEach((b,i)=>{const m=MEMORIES[slots[i]];b.innerHTML='<span>'+(m?.icon||'＋')+'</span><b>'+(m?.name||(i+1)+'번째 자리')+'</b>';b.setAttribute('aria-label',(i+1)+'번째 자리 · '+(m?.name||'선택한 기억 걸기'))});d.querySelectorAll('[data-final-memory]').forEach(b=>{b.setAttribute('aria-pressed',String(selected===b.dataset.finalMemory));b.dataset.hanging=String(slots.includes(b.dataset.finalMemory))});d.querySelectorAll('[data-final-ribbon]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.finalRibbon===ribbon)))}
 function persist(){if(!dirty||!owned())return;try{localStorage.setItem(draftKey(),JSON.stringify({v:1,slots,ribbon}))}catch{status('기기 임시저장을 하지 못했어요. 아래 마무리 버튼으로 수첩에 저장해 주세요.')}}
 function change(){dirty=true;preview();status('미리보기예요. 마음에 들면 아래에서 이야기 마무리를 눌러요.');persist()}
 function place(i){if(!selected||!state.earned.includes(selected)||i<0||i>2)return;slots=slots.map(x=>x===selected?null:x);slots[i]=selected;selected=null;change()}
 function finish(){ribbon=state.ribbon;open('함께 자란 두 번째 모험을 기억해요.',teacher('“너의 도움이 누군가의 웃음이 되고, 작은 발견은 멋진 이야기가 되었구나. 앞으로도 네 속도로 학교를 탐험하자!”')+flags(state.memories)+'<div class="finale-award" data-ribbon="'+state.ribbon+'"><span class="finale-rosette" aria-hidden="true">✦</span><div><h3>함께 자란 모험가</h3><p>'+RIBBONS[state.ribbon]+' 기념 리본을 모았어요.</p></div></div><ul class="finale-recall">'+state.memories.map(id=>'<li>'+MEMORIES[id].text+'</li>').join('')+'</ul><p>내 교실 산책 화면에도 이 가랜드가 걸렸어요.<br>배움과 친절로 남긴 기억을 다시 펼쳐 볼 수 있어요.</p><button data-final="edit">가랜드 다시 꾸미기</button> <button data-final="wear">'+(state.wearing?'프로필 리본 보관하기':'프로필에 리본 달기')+'</button>'+feedback()+'<p class="parcel-note">이야기 기념 장식이에요. 능력치·경험치·골드는 바뀌지 않아요. Lv.20의 50 G는 기존 레벨 선물에서 한 번 받아요.</p><button data-final="close">학교 산책 계속하기</button>')}
 async function save(action){if(busy||!owned())return;if(action==='save'&&(!validSlots(slots)||slots.some(x=>!x))){status('서로 다른 기억 세 가지를 빈자리에 걸어 주세요.');return}persist();const id=owner,t=token,g=epoch,values=slots.slice(),color=ribbon,wear=!state.wearing;busy=true;readVersion++;const buttons=[...d.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);status('학교의 기억을 수첩에 저장하고 있어요…');
  try{const {data,error}=await c.db.rpc('student_school_finale',{p_token:t,p_action:action,p_memories:action==='save'?values:null,p_ribbon:action==='save'?color:null,p_wearing:action==='wear'?wear:null});if(g!==epoch||id!==c.getStudent()?.id||t!==c.getToken())return;if(error||!validState(data)||!data.completed_at||action==='save'&&(data.ribbon!==color||JSON.stringify(data.memories)!==JSON.stringify(values))||action==='wear'&&data.wearing!==wear)throw error||Error('Unconfirmed memory');state=data;loaded=true;dirty=false;try{localStorage.removeItem(draftKey())}catch{}updateWorld();finish();status(action==='wear'?'✓ 리본의 착용 상태를 저장했어요.':'✓ 가랜드와 두 번째 모험의 기억을 저장했어요.');
  }catch{if(g===epoch&&owned())status('저장을 확인하지 못했어요. 꾸민 모습은 그대로예요. 연결을 확인하고 다시 눌러 주세요.')}finally{if(g===epoch){busy=false;buttons.forEach(b=>{if(b.isConnected)b.disabled=false})}}
 }
 d.addEventListener('click',e=>{if(ignoreClick){ignoreClick=false;return}if(busy)return;const b=e.target.closest('button');if(!b)return;if(!owned()){reset();return}const a=b.dataset.final;
  if(a==='close'){persist();d.close();return}if(a==='retry'){start();return}if(a==='edit'){begin();return}if(a==='save'||a==='wear'){save(a);return}if(a==='clear'){slots=[null,null,null];selected=null;change();return}
  if(b.dataset.finalVisit){persist();d.close();window.studentAdventure.workshop(MEMORIES[b.dataset.finalVisit].activity);return}
  if(b.dataset.finalMemory){selected=b.dataset.finalMemory;preview();status('걸어 둘 자리를 눌러 주세요.');return}if(b.dataset.finalRibbon){ribbon=b.dataset.finalRibbon;change();return}
  if(b.hasAttribute('data-final-slot')){const i=Number(b.dataset.finalSlot);if(selected)place(i);else{slots[i]=null;change()}}
 });
 d.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-final-memory]');if(!b||busy||e.button!==0)return;drag={id:e.pointerId,memory:b.dataset.finalMemory,x:e.clientX,y:e.clientY,moved:false};b.setPointerCapture(e.pointerId)});
 d.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>8){drag.moved=true;selected=drag.memory;preview();d.querySelectorAll('[data-final-slot]').forEach(b=>b.classList.toggle('finale-over',b===doc.elementFromPoint(e.clientX,e.clientY)?.closest('[data-final-slot]')))}});
 d.addEventListener('pointerup',e=>{if(!drag||e.pointerId!==drag.id)return;const moved=drag.moved;drag=null;d.querySelectorAll('.finale-over').forEach(b=>b.classList.remove('finale-over'));if(moved){const slot=doc.elementFromPoint(e.clientX,e.clientY)?.closest('[data-final-slot]');if(slot)place(Number(slot.dataset.finalSlot));ignoreClick=true;setTimeout(()=>ignoreClick=false,0)}});
 for(const name of ['pointercancel','lostpointercapture'])d.addEventListener(name,()=>{drag=null;d.querySelectorAll('.finale-over').forEach(b=>b.classList.remove('finale-over'))});
 d.addEventListener('cancel',e=>{if(busy)e.preventDefault();else persist()});d.addEventListener('close',()=>{view++;drag=null;if(opener?.isConnected&&opener.getClientRects().length)opener.focus({preventScroll:true})});
 doc.addEventListener('student-dashboard-updated',()=>{if(!owned())reset();load()});window.addEventListener('pagehide',persist);queueMicrotask(()=>load());
 return {start,completed,label:lv=>completed()?'✓ 두 번째 이야기 · 기억 다시 꾸미기':lv<20?'🔒 Lv.20에 열려요':'마음에 남는 기억 세 가지 걸기',profile:()=>completed()&&state.wearing?'<button class="sa-profile-memento finale-profile" data-workshop="school-finale" data-ribbon="'+state.ribbon+'"><span class="finale-rosette" aria-hidden="true">✦</span><span>함께 자란 모험가<br><small>'+RIBBONS[state.ribbon]+' · 두 번째 이야기 리본</small></span></button>':''};
}
