const frame=document.getElementById('app');
const IDLE_LIMIT=30*60*1000;
const NOTICE_POLL_MS=60*1000;
const APP_VERSION='v0.9.15';
let idleTimer,noticeTimer,noticeShowing=false,retryReviewId=null;

function resetIdle(){clearTimeout(idleTimer);idleTimer=setTimeout(()=>{try{frame.contentWindow.localStorage.removeItem('classRpgStudentToken')}catch{}location.reload()},IDLE_LIMIT)}
function getCore(){try{return frame.contentDocument?.getElementById('core')?.contentWindow||null}catch{return null}}
function installNetworkBanner(){const d=frame.contentDocument;if(!d||d.querySelector('.network-banner'))return;const s=d.createElement('style');s.textContent='.network-banner{position:fixed;left:50%;top:10px;transform:translateX(-50%);z-index:9999;padding:8px 12px;border-radius:999px;background:#fff3d5;color:#7a5600;font-weight:900;box-shadow:0 4px 12px #0002}.network-banner.hidden{display:none!important}';d.head.appendChild(s);const b=d.createElement('div');b.className='network-banner hidden';b.textContent='📶 인터넷 연결이 불안정해요. 로그인은 유지할게요.';d.body.appendChild(b);const sync=()=>b.classList.toggle('hidden',frame.contentWindow.navigator.onLine);frame.contentWindow.addEventListener('online',sync);frame.contentWindow.addEventListener('offline',sync);sync()}
function installCorePolish(){const w=getCore(),d=w?.document;if(!d||d.getElementById('runtimePolish'))return;const s=d.createElement('style');s.id='runtimePolish';s.textContent='.profile{grid-template-columns:280px minmax(0,1fr)!important}.avatar-actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:7px!important}.avatar-actions .btn{width:100%!important;min-width:0!important;font-size:13px!important;padding:10px 4px!important}.avatar-actions .map-btn{grid-column:1/-1!important}.quest-head>button[onclick="loadDashboard()"]{display:none!important}.rpg-version{position:fixed;right:10px;bottom:8px;z-index:60;padding:4px 7px;border-radius:999px;background:#ffffffcc;border:1px solid #eadfd5;color:#9a8d84;font-size:10px;font-weight:800;pointer-events:none}.reward-notice-backdrop{position:fixed;inset:0;z-index:13000;display:grid;place-items:center;padding:18px;background:#2d254b99}.reward-notice-card{position:relative;width:min(430px,100%);padding:24px;border:3px solid #f1c15c;border-radius:26px;background:#fffdf6;text-align:center}.reward-notice-card.rejected{border-color:#ee9aa7}.reward-notice-close{position:absolute;right:13px;top:11px;width:34px;height:34px;border:0;border-radius:50%;background:#eee8ff;color:#5b50bd;font-size:18px}.reward-notice-icon{font-size:52px}.reward-chips{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin:16px 0}.reward-chip{padding:8px 11px;border-radius:999px;background:#fff3d5;color:#946000;font-weight:900}.reward-confirm{border:0;border-radius:13px;padding:11px 18px;background:#e4f7ed;color:#18784c;font-weight:900}.reading-retry-btn{margin-top:9px;border:0;border-radius:11px;padding:8px 11px;background:#fff0f3;color:#a33650;font-weight:900}@media(max-width:650px){.profile{grid-template-columns:1fr!important}}';d.head.appendChild(s);const v=d.createElement('div');v.className='rpg-version';v.textContent=APP_VERSION;d.body.appendChild(v)}
function installBusyGuard(){const w=getCore(),d=w?.document;if(!d||d.__busyGuard)return;d.__busyGuard=true;d.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled||b.dataset.busy==='1')return;if(b.matches('button[onclick*="login"],.shop-item .btn,.quest .btn,.reading-form .btn,.title-equip-btn')){b.dataset.busy='1';setTimeout(()=>b.dataset.busy='0',1200)}},true)}
function installDashboardLock(){const w=getCore();if(!w||w.__dashboardLoadLocked||typeof w.loadDashboard!=='function')return;w.__dashboardLoadLocked=true;const base=w.loadDashboard;let running=null,lastAt=0;w.loadDashboard=(...args)=>{const now=Date.now();if(running)return running;if(now-lastAt<500)return Promise.resolve();lastAt=now;running=Promise.resolve(base(...args)).catch(e=>{console.warn('dashboard refresh skipped',e);return null}).finally(()=>{running=null});return running}}
function noticeView(n){const ok=n.status==='approved',reading=n.kind==='reading',bonus=n.kind==='bonus';if(bonus)return{icon:'🎁',title:'선생님 보너스!',text:`${n.reason||'멋진 활동을 해서 보너스를 받았어요!'}\n경험치와 골드가 지급됐어요.`};if(ok&&reading)return{icon:'📚',title:'독후감 승인!',text:`“${n.title||'독후감'}”이 승인됐어요!`};if(ok)return{icon:'🏆',title:'퀘스트 완료!',text:`“${n.title||'퀘스트'}”가 승인됐어요!`};if(reading)return{icon:'📝',title:'독후감이 반려됐어요',text:`“${n.title||'독후감'}”을 수정해서 다시 제출해 주세요.${n.reason?'\n선생님: '+n.reason:''}`};return{icon:'↩️',title:'퀘스트가 반려됐어요',text:`“${n.title||'퀘스트'}”를 다시 도전해 주세요.${n.reason?'\n선생님: '+n.reason:''}`}}
async function showRewardQueue(items){if(noticeShowing||!items?.length)return;const w=getCore(),d=w?.document;if(!w||!d)return;noticeShowing=true;try{for(const n of items){const view=noticeView(n),ok=n.status==='approved'||n.kind==='bonus';const back=d.createElement('div');back.className='reward-notice-backdrop';back.innerHTML=`<section class="reward-notice-card ${ok?'':'rejected'}"><button class="reward-notice-close">✕</button><div class="reward-notice-icon">${view.icon}</div><h2>${view.title}</h2><p style="white-space:pre-line"></p>${ok?`<div class="reward-chips"><span class="reward-chip">✨ +${Number(n.xp||0)} XP</span><span class="reward-chip">🪙 +${Number(n.gold||0)} G</span></div>`:''}<button class="reward-confirm">확인</button></section>`;back.querySelector('p').textContent=view.text;d.body.appendChild(back);await new Promise(r=>{back.querySelector('.reward-notice-close').onclick=r;back.querySelector('.reward-confirm').onclick=r});try{const token=localStorage.getItem('classRpgStudentToken')||'';if(token&&w.db?.rpc)await w.db.rpc('student_ack_notification',{p_token:token,p_kind:n.kind||'quest',p_id:Number(n.id||n.submission_id)})}catch{}back.remove()}}finally{noticeShowing=false}try{await w.loadDashboard?.()}catch{}}
async function pollRewardNotices(){if(noticeShowing||document.hidden)return;const w=getCore(),d=w?.document;if(!w?.db?.rpc||!d)return;const dash=d.getElementById('dashboard');if(!dash||dash.classList.contains('hidden')||d.querySelector('.modal-backdrop:not(.hidden),.reward-notice-backdrop'))return;const token=localStorage.getItem('classRpgStudentToken')||'';if(!token)return;try{const{data,error}=await w.db.rpc('student_dashboard',{p_token:token});if(!error&&data?.reward_notifications?.length)await showRewardQueue(data.reward_notifications)}catch{}}
function installReadingRetry(){const w=getCore(),d=w?.document;if(!w||!d||w.__readingRetryInstalled)return;w.__readingRetryInstalled=true;const baseOpen=w.openReadingPortfolio;if(typeof baseOpen==='function')w.openReadingPortfolio=async(...args)=>{retryReviewId=null;const out=await baseOpen(...args);setTimeout(()=>decorateReadingRetries(),100);return out};const baseSave=w.saveReadingEntry;if(typeof baseSave==='function')w.saveReadingEntry=async(...args)=>{if(!retryReviewId)return baseSave(...args);const token=localStorage.getItem('classRpgStudentToken')||'',p={p_token:token,p_review_id:retryReviewId,p_book_title:d.getElementById('readingBookTitle')?.value?.trim()||'',p_read_date:d.getElementById('readingDate')?.value||'',p_summary:d.getElementById('readingSummary')?.value?.trim()||'',p_thoughts:d.getElementById('readingThought')?.value?.trim()||'',p_recommendation_rating:Number(d.getElementById('readingRating')?.value||5),p_recommendation_reason:d.getElementById('readingRecommendation')?.value?.trim()||''};const{error}=await w.db.rpc('student_retry_reading_review',p);const msg=d.getElementById('readingPortfolioMsg');if(error){if(msg){msg.className='message error';msg.textContent=error.message}return}retryReviewId=null;if(msg){msg.className='message ok';msg.textContent='다시 제출했어요!'}setTimeout(()=>w.openReadingPortfolio(),300)}}
async function decorateReadingRetries(){const w=getCore(),d=w?.document;if(!w?.db?.rpc||!d)return;const history=d.getElementById('readingHistory'),modal=d.getElementById('readingPortfolioModal');if(!history||!modal||modal.classList.contains('hidden'))return;const token=localStorage.getItem('classRpgStudentToken')||'';if(!token)return;const{data,error}=await w.db.rpc('student_reading_reviews_v2',{p_token:token});if(error||!Array.isArray(data))return;[...history.querySelectorAll('.reading-entry')].forEach((entry,i)=>{const r=data[i];if(!r||r.status!=='rejected'||entry.querySelector('.reading-retry-btn'))return;const b=d.createElement('button');b.className='reading-retry-btn';b.textContent='↩️ 수정해서 다시 제출하기';b.onclick=()=>{retryReviewId=r.review_id;d.getElementById('readingBookTitle').value=r.book_title||'';d.getElementById('readingDate').value=r.read_date||'';d.getElementById('readingSummary').value=r.summary||'';d.getElementById('readingThought').value=r.thoughts||'';d.getElementById('readingRating').value=String(r.recommendation_rating||5);d.getElementById('readingRecommendation').value=r.recommendation_reason||'';d.querySelector('.reading-form')?.scrollIntoView({block:'start'})};entry.appendChild(b)})}
function install(){try{installNetworkBanner();const cf=frame.contentDocument?.getElementById('core');if(cf&&!cf.__fastHooked){cf.__fastHooked=true;cf.addEventListener('load',()=>setTimeout(()=>{installCorePolish();installBusyGuard();installDashboardLock();installReadingRetry();pollRewardNotices()},150))}setTimeout(()=>{installCorePolish();installBusyGuard();installDashboardLock();installReadingRetry();pollRewardNotices()},450)}catch(e){console.warn(e)}}
['click','keydown','pointerdown','touchstart'].forEach(t=>window.addEventListener(t,resetIdle,{passive:true}));frame.addEventListener('load',install);window.addEventListener('focus',()=>setTimeout(pollRewardNotices,250));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(pollRewardNotices,250)});resetIdle();noticeTimer=setInterval(pollRewardNotices,NOTICE_POLL_MS);
