-- 우리반 RPG: 독후감 포트폴리오 + 주 3편 제한 + 보상
-- Supabase SQL Editor에서 이 파일 전체를 한 번 실행하세요.
begin;

create table if not exists public.reading_reviews (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  book_title text not null check(char_length(book_title) between 1 and 80),
  read_date date not null,
  summary text not null check(char_length(summary) between 1 and 2000),
  thoughts text not null check(char_length(thoughts) between 1 and 2000),
  recommendation_rating smallint not null check(recommendation_rating between 1 and 5),
  recommendation_reason text not null check(char_length(recommendation_reason) between 1 and 500),
  created_at timestamptz not null default now()
);
create index if not exists reading_reviews_student_created_idx on public.reading_reviews(student_id,created_at desc);
alter table public.reading_reviews enable row level security;
revoke all on public.reading_reviews from anon,authenticated;

create or replace function public.student_reading_reviews(p_token text)
returns table(review_id bigint,book_title text,read_date date,summary text,thoughts text,recommendation_rating smallint,recommendation_reason text,created_at timestamptz)
language plpgsql security definer set search_path=public stable as $$
declare v_student_id bigint;
begin
  v_student_id:=public.student_for_token(p_token);
  if v_student_id is null then raise exception '로그인이 만료됐어요. 다시 로그인해 주세요.'; end if;
  return query
    select r.id,r.book_title,r.read_date,r.summary,r.thoughts,r.recommendation_rating,r.recommendation_reason,r.created_at
    from public.reading_reviews r where r.student_id=v_student_id order by r.created_at desc;
end; $$;
revoke all on function public.student_reading_reviews(text) from public;
grant execute on function public.student_reading_reviews(text) to anon,authenticated;

create or replace function public.student_add_reading_review(
  p_token text,p_book_title text,p_read_date date,p_summary text,p_thoughts text,
  p_recommendation_rating smallint,p_recommendation_reason text
)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_student_id bigint; v_week_count integer; v_xp integer; v_gold integer;
begin
  v_student_id:=public.student_for_token(p_token);
  if v_student_id is null then raise exception '로그인이 만료됐어요. 다시 로그인해 주세요.'; end if;
  if coalesce(length(trim(p_book_title)),0)=0 or coalesce(length(trim(p_summary)),0)=0 or coalesce(length(trim(p_thoughts)),0)=0 or coalesce(length(trim(p_recommendation_reason)),0)=0 then
    raise exception '모든 독후감 항목을 적어 주세요.';
  end if;
  if p_recommendation_rating not between 1 and 5 then raise exception '추천 별점을 골라 주세요.'; end if;
  select count(*) into v_week_count from public.reading_reviews
    where student_id=v_student_id and created_at>=date_trunc('week',now());
  if v_week_count>=3 then raise exception '이번 주에는 독후감을 3편까지 기록했어요. 다음 주에 다시 도전해요!'; end if;
  insert into public.reading_reviews(student_id,book_title,read_date,summary,thoughts,recommendation_rating,recommendation_reason)
    values(v_student_id,trim(p_book_title),p_read_date,trim(p_summary),trim(p_thoughts),p_recommendation_rating,trim(p_recommendation_reason));
  update public.students set xp=xp+10,gold=gold+30 where id=v_student_id returning xp,gold into v_xp,v_gold;
  return jsonb_build_object('ok',true,'xp',v_xp,'gold',v_gold,'reward_xp',10,'reward_gold',30);
end; $$;
revoke all on function public.student_add_reading_review(text,text,date,text,text,smallint,text) from public;
grant execute on function public.student_add_reading_review(text,text,date,text,text,smallint,text) to anon,authenticated;

commit;
