const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function installReadingShelf(c){
 const doc=document,dialog=doc.createElement('dialog');dialog.id='readingShelf';dialog.className='reading-shelf';dialog.setAttribute('aria-labelledby','readingShelfTitle');doc.body.append(dialog);
 let owner=null,pin=null,scope='mine',rows=[],cursor=null,more=false,busy=false,generation=0,opener=null;
 const owned=()=>owner===c.getStudent()?.id&&pin===c.getToken();
 function shell(){dialog.innerHTML='<header><div><span>이야기 도서관 · 함께 읽는 책장</span><h2 id="readingShelfTitle">우리 반 독후감 책장</h2></div><button data-shelf-close autofocus>닫기</button></header><p class="shelf-intro">책장을 펼쳐 나와 친구들의 생각을 읽어 보세요.</p><nav class="shelf-tabs" aria-label="읽을 글 선택"><button data-shelf-scope="mine" aria-pressed="'+(scope==='mine')+'">📘 내가 쓴 글</button><button data-shelf-scope="class" aria-pressed="'+(scope==='class')+'">📚 우리 반 친구 글</button></nav><p class="shelf-note">친구 글은 선생님이 확인한 독후감을 함께 읽어요. 확인 중인 내 글은 내 책장에서 볼 수 있어요.</p><div id="shelfRows"></div><div id="shelfStatus" role="status" aria-live="polite"></div><footer><button data-shelf-more hidden>이전 글 더 보기</button><button data-shelf-write>✍️ 책상에서 새 독후감 쓰기</button></footer>'}
 function render(){doc.getElementById('shelfRows').innerHTML=rows.length?'<div class="shelf-books">'+rows.map(r=>'<article class="shelf-book"><div class="shelf-book-cover" aria-hidden="true">📖</div><div><h3>'+esc(r.book_title)+'</h3><p class="shelf-author">'+esc(r.author_nickname)+(r.mine?' · 내 글':'')+' · '+esc(r.read_date)+'</p><span class="shelf-review-state">'+(r.mine?({submitted:'선생님 확인 중',rejected:'조금 더 다듬어요',approved:'확인 완료'}[r.status]||''):'친구가 나눈 책 이야기')+'</span><details><summary>독후감 읽기</summary><div class="shelf-review"><h4>책 이야기</h4><p>'+esc(r.summary)+'</p><h4>나는 이렇게 생각했어요</h4><p>'+esc(r.thoughts)+'</p><h4>추천하는 까닭</h4><p>'+esc(r.recommendation_reason)+'</p><span>'+'★'.repeat(Math.max(0,Math.min(5,Number(r.recommendation_rating)||0)))+'</span></div></details>'+(r.mine&&r.status==='rejected'?'<button data-shelf-edit="'+Number(r.review_id)+'">내 글 다듬기</button>':'')+'</div></article>').join('')+'</div>':'<div class="shelf-empty">'+(scope==='mine'?'아직 저장한 독후감이 없어요. 책상에서 첫 글을 써 볼까요?':'함께 읽을 독후감을 기다리고 있어요. 선생님이 확인하면 이 책장에 보여요.')+'</div>';const b=dialog.querySelector('[data-shelf-more]');b.hidden=!more;b.disabled=busy;}
 async function load(append=false){if(busy)return;const request=++generation,who=owner,token=pin;busy=true;const status=doc.getElementById('shelfStatus');status.textContent='책 이야기를 펼치는 중이에요…';dialog.querySelector('[data-shelf-more]').disabled=true;
  try{const {data,error}=await c.db.rpc('student_reading_shelf',{p_token:token,p_scope:scope,p_before_id:append?cursor:null});if(error||!Array.isArray(data?.reviews))throw error||Error('missing shelf');if(request!==generation||!owned()||who!==owner||!dialog.open)return;rows=append?[...rows,...data.reviews]:data.reviews;cursor=data.next_before_id;more=data.has_more===true;render();status.textContent=rows.length+'편을 펼쳤어요.'}
  catch{if(request===generation&&owned()&&dialog.open)status.innerHTML='책장을 아직 불러오지 못했어요. <button data-shelf-retry>다시 펼치기</button>'}
  finally{if(request===generation){busy=false;const b=dialog.querySelector('[data-shelf-more]');if(b)b.disabled=false}}
 }
 function open(){generation++;owner=c.getStudent()?.id;pin=c.getToken();if(!owner)return;scope='mine';rows=[];cursor=null;more=false;busy=false;opener=doc.activeElement;shell();render();if(!dialog.open)dialog.showModal();load()}
 function close(){generation++;busy=false;dialog.close()}
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-shelf-close')){close();return}if(!owned()){close();return}if(b.dataset.shelfScope){generation++;scope=b.dataset.shelfScope;rows=[];cursor=null;more=false;busy=false;shell();render();dialog.querySelector('[data-shelf-scope="'+scope+'"]').focus();load();return}if(b.hasAttribute('data-shelf-more'))load(true);if(b.hasAttribute('data-shelf-retry'))load(rows.length>0);if(b.hasAttribute('data-shelf-write')||b.dataset.shelfEdit){close();c.write(b.dataset.shelfEdit||null)}});
 dialog.addEventListener('cancel',()=>{generation++;busy=false});dialog.addEventListener('close',()=>{generation++;busy=false;if(opener?.isConnected&&opener.getClientRects().length)opener.focus({preventScroll:true})});
 doc.addEventListener('student-dashboard-updated',()=>{if(owner!==null&&!owned()){generation++;rows=[];busy=false;dialog.replaceChildren();if(dialog.open)dialog.close()}});
 window.openReadingShelf=open;return {open,close};
}
