-- 우리반 RPG: 학생 로그인 목록 + 골드 상점 + 실물 교환 요청
-- Supabase SQL Editor에서 이 파일 전체를 한 번 실행하세요.
begin;

create or replace function public.student_login_options()
returns table (student_number integer, login_id text, nickname text)
language sql security definer set search_path=public stable as $$
  select s.student_number,s.login_id,s.nickname from public.students s order by s.student_number;
$$;
revoke all on function public.student_login_options() from public;
grant execute on function public.student_login_options() to anon,authenticated;

create table if not exists public.shop_products (
  id text primary key,
  category text not null check(category in ('weapon','armor','top','bottom','shoes','misc')),
  kind text not null default 'coupon' check(kind in ('coupon','wearable')),
  name text not null, description text not null default '', icon text not null default '🎁', image text,
  price integer not null check(price>=0), active boolean not null default true,
  stock integer check(stock is null or stock>=0), per_student_limit integer check(per_student_limit is null or per_student_limit>0),
  item_id text, sort_order integer not null default 0, created_at timestamptz not null default now()
);
alter table public.shop_products add column if not exists gender text;
do $$ begin
  if not exists (select 1 from pg_constraint where conname='shop_products_gender_check') then
    alter table public.shop_products add constraint shop_products_gender_check check(gender in ('boy','girl') or gender is null);
  end if;
end $$;
create table if not exists public.shop_orders (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  product_id text not null references public.shop_products(id), price integer not null check(price>=0),
  status text not null default 'pending' check(status in ('pending','used','cancelled')),
  created_at timestamptz not null default now(), resolved_at timestamptz, resolved_by uuid references auth.users(id)
);
create index if not exists shop_orders_student_idx on public.shop_orders(student_id,status);
create index if not exists shop_orders_status_idx on public.shop_orders(status,created_at);
alter table public.shop_products enable row level security;
alter table public.shop_orders enable row level security;
revoke all on public.shop_products,public.shop_orders from anon,authenticated;

insert into public.shop_products(id,category,kind,name,description,icon,price,sort_order) values
 ('vitamin','misc','coupon','비타민','선생님께 비타민 1개를 받아요.','🍊',20,10),
 ('chromebook-pass','misc','coupon','크롬북 이용권','정해진 시간에 크롬북을 이용해요.','💻',60,20),
 ('music-choice','misc','coupon','교실 음악 신청권','쉬는 시간에 들을 음악 1곡을 신청해요.','🎵',30,30),
 ('seat-choice','misc','coupon','자리 선택권','선생님과 상의해 원하는 자리를 골라요.','🪑',80,40),
 ('sticker','misc','coupon','칭찬 스티커','칭찬 스티커 1개와 교환해요.','⭐',40,50),
 ('nickname-change','misc','coupon','닉네임 변경권','RPG 캐릭터 닉네임을 한 번 바꿔요.','✏️',150,60)
on conflict(id) do update set category=excluded.category,kind=excluded.kind,name=excluded.name,
 description=excluded.description,icon=excluded.icon,price=excluded.price,sort_order=excluded.sort_order,active=true;

-- 교복은 구매 즉시 '내 아이템'에 들어가며, 같은 성별의 학생에게만 보여요.
-- 기존 RPG 아이템 표는 boy_image / girl_image 칸을 사용합니다.
insert into public.item_catalog(id,name,slot,boy_image,girl_image,price,active,default_owned,default_equipped) values
 ('school-top-boy','남자 교복 상의','top','3.top/top_boy_school.png','3.top/top_girl_school.png',80,true,false,false),
 ('school-bottom-boy','남자 교복 하의','bottom','4.bottom/bottom_boy_school.png','4.bottom/bottom_girl_school.png',70,true,false,false),
 ('school-top-girl','여자 교복 상의','top','3.top/top_boy_school.png','3.top/top_girl_school.png',80,true,false,false),
 ('school-bottom-girl','여자 교복 하의','bottom','4.bottom/bottom_boy_school.png','4.bottom/bottom_girl_school.png',70,true,false,false)
on conflict(id) do update set name=excluded.name,slot=excluded.slot,boy_image=excluded.boy_image,
 girl_image=excluded.girl_image,price=excluded.price,active=true,default_owned=false,default_equipped=false;

-- 기본 아이템 이름을 학생 화면에서 쓰는 말로 다듬습니다.
update public.item_catalog set name='기본 흰색 상의' where id='basic_top';
update public.item_catalog set name='기본 파란색 하의' where id='basic_bottom';
update public.item_catalog set name='기본 운동화' where id='basic_shoes';

insert into public.shop_products(id,category,kind,name,description,icon,image,price,item_id,sort_order,gender) values
 ('school-top-boy','top','wearable','남자 교복 상의','깔끔한 남색 반팔 교복 상의예요.','👔','3.top/top_boy_school.png',80,'school-top-boy',10,'boy'),
 ('school-top-girl','top','wearable','여자 교복 상의','리본이 달린 남색 반팔 교복 상의예요.','🎀','3.top/top_girl_school.png',80,'school-top-girl',20,'girl'),
 ('school-bottom-boy','bottom','wearable','남자 교복 하의','교복 상의와 잘 어울리는 하의예요.','👖','4.bottom/bottom_boy_school.png',70,'school-bottom-boy',10,'boy'),
 ('school-bottom-girl','bottom','wearable','여자 교복 하의','교복 상의와 잘 어울리는 하의예요.','👖','4.bottom/bottom_girl_school.png',70,'school-bottom-girl',20,'girl')
on conflict(id) do update set category=excluded.category,kind=excluded.kind,name=excluded.name,
 description=excluded.description,icon=excluded.icon,image=excluded.image,price=excluded.price,
 item_id=excluded.item_id,sort_order=excluded.sort_order,gender=excluded.gender,active=true;

create or replace function public.student_shop(p_token text)
returns table(product_id text,category text,kind text,name text,description text,icon text,image text,price integer,owned boolean)
language plpgsql security definer set search_path=public stable as $$
declare v_student public.students%rowtype; v_student_id bigint;
begin
  v_student_id:=public.student_for_token(p_token);
  if v_student_id is null then raise exception '로그인이 만료됐어요. 다시 로그인해 주세요.'; end if;
  select * into v_student from public.students where id=v_student_id;
  return query select p.id,p.category,p.kind,p.name,p.description,p.icon,p.image,p.price,
    case when p.kind='wearable' then exists(select 1 from public.student_items si where si.student_id=v_student.id and si.item_id=p.item_id)
         else exists(select 1 from public.shop_orders o where o.student_id=v_student.id and o.product_id=p.id and o.status='pending') end
  from public.shop_products p where p.active and (p.stock is null or p.stock>0)
    and (p.gender is null or p.gender=v_student.gender)
    and (p.kind='wearable' or p.per_student_limit is null or (select count(*) from public.shop_orders o where o.student_id=v_student.id and o.product_id=p.id and o.status<>'cancelled')<p.per_student_limit)
  order by p.sort_order,p.price,p.name;
end; $$;
revoke all on function public.student_shop(text) from public;
grant execute on function public.student_shop(text) to anon,authenticated;

create or replace function public.student_buy_product(p_token text,p_product_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_student public.students%rowtype; v_student_id bigint; v_product public.shop_products%rowtype; v_order_id bigint;
begin
  v_student_id:=public.student_for_token(p_token);
  if v_student_id is null then raise exception '로그인이 만료됐어요. 다시 로그인해 주세요.'; end if;
  select * into v_student from public.students where id=v_student_id;
  select * into v_product from public.shop_products where id=p_product_id and active for update;
  if v_product.id is null then raise exception '판매하지 않는 상품이에요.'; end if;
  if v_product.gender is not null and v_product.gender<>v_student.gender then raise exception '내 캐릭터에게 맞지 않는 옷이에요.'; end if;
  if v_product.stock is not null and v_product.stock<1 then raise exception '상품이 품절됐어요.'; end if;
  if v_product.kind='wearable' and (v_product.item_id is null or v_product.item_id='') then raise exception '이 옷의 아이템 정보가 없어요.'; end if;
  if v_product.kind='wearable' and exists(select 1 from public.student_items where student_id=v_student.id and item_id=v_product.item_id) then raise exception '이미 가지고 있는 옷이에요.'; end if;
  if v_product.kind='coupon' and exists(select 1 from public.shop_orders where student_id=v_student.id and product_id=v_product.id and status='pending') then raise exception '이미 교환을 요청한 상품이에요.'; end if;
  if v_product.kind='coupon' and v_product.per_student_limit is not null and (select count(*) from public.shop_orders where student_id=v_student.id and product_id=v_product.id and status<>'cancelled')>=v_product.per_student_limit then raise exception '구매 가능 횟수를 모두 사용했어요.'; end if;
  update public.students set gold=gold-v_product.price where id=v_student.id and gold>=v_product.price;
  if not found then raise exception '골드가 부족해요.'; end if;
  if v_product.kind='wearable' then
    insert into public.student_items(student_id,item_id) values(v_student.id,v_product.item_id);
    if v_product.stock is not null then update public.shop_products set stock=stock-1 where id=v_product.id; end if;
    return jsonb_build_object('ok',true,'item_id',v_product.item_id,'price',v_product.price);
  end if;
  insert into public.shop_orders(student_id,product_id,price) values(v_student.id,v_product.id,v_product.price) returning id into v_order_id;
  if v_product.stock is not null then update public.shop_products set stock=stock-1 where id=v_product.id; end if;
  return jsonb_build_object('ok',true,'order_id',v_order_id,'price',v_product.price);
end; $$;
revoke all on function public.student_buy_product(text,text) from public;
grant execute on function public.student_buy_product(text,text) to anon,authenticated;

create or replace function public.teacher_shop_orders()
returns table(order_id bigint,student_number integer,student_name text,product_name text,product_icon text,price integer,created_at timestamptz)
language sql security definer set search_path=public stable as $$
  select o.id,s.student_number,s.nickname,p.name,p.icon,o.price,o.created_at
  from public.shop_orders o join public.students s on s.id=o.student_id join public.shop_products p on p.id=o.product_id
  where s.teacher_id=auth.uid() and o.status='pending' order by o.created_at;
$$;
revoke all on function public.teacher_shop_orders() from public;
grant execute on function public.teacher_shop_orders() to authenticated;

create or replace function public.teacher_resolve_shop_order(p_order_id bigint,p_status text)
returns void language plpgsql security definer set search_path=public as $$
declare v_order public.shop_orders%rowtype;
begin
  if p_status not in ('used','cancelled') then raise exception '처리 상태가 올바르지 않아요.'; end if;
  select o.* into v_order from public.shop_orders o join public.students s on s.id=o.student_id
  where o.id=p_order_id and o.status='pending' and s.teacher_id=auth.uid() for update of o;
  if v_order.id is null then raise exception '처리할 교환 요청을 찾지 못했어요.'; end if;
  update public.shop_orders set status=p_status,resolved_at=now(),resolved_by=auth.uid() where id=v_order.id;
  if p_status='cancelled' then
    update public.students set gold=gold+v_order.price where id=v_order.student_id;
    update public.shop_products set stock=stock+1 where id=v_order.product_id and stock is not null;
  end if;
end; $$;
revoke all on function public.teacher_resolve_shop_order(bigint,text) from public;
grant execute on function public.teacher_resolve_shop_order(bigint,text) to authenticated;

commit;
