const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1366,height:900},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);const f=page.frames().find(f=>f.url().includes('app-core'));await f.waitForFunction(()=>window.studentCampus);fs.mkdirSync(shots,{recursive:true});await f.evaluate(()=>enterHubScene('library'));
 await f.locator('[data-place=reading]').click();assert(await f.locator('#readingEntryForm').isVisible());assert(await f.locator('#readingHistory').isHidden());assert.match(await f.locator('#readingJournalTitle').textContent(),/쓰/);await f.locator('#readingBookTitle').fill('내가 쓰던 책');await f.locator('#readingSummary').fill('쓰던 줄거리를 보관해요.');await page.keyboard.press('Escape');
 await f.locator('[data-place=portfolio]').click();assert(await f.locator('#readingShelf').isVisible());assert(!await f.locator('#readingEntryForm').isVisible());await f.locator('.shelf-book').first().waitFor();assert.equal(await f.locator('.shelf-book').count(),2);await f.locator('#readingShelf summary').first().click();assert.match(await f.locator('#shelfRows').textContent(),/매일 돌봐|서로 도우면/);await f.locator('[data-shelf-scope=class]').tap();await f.locator('.shelf-book').waitFor();assert.match(await f.locator('#shelfRows').textContent(),/초록별/);assert.equal(await f.locator('[data-shelf-edit]').count(),0);
 await f.evaluate(()=>{mockRpg.shelfReviews=Array.from({length:23},(_,i)=>({review_id:100-i,book_title:i===0?'<img src=x onerror="window.shelfXss=1">':'친구의 책 '+i,read_date:'2026-10-07',summary:'책 속 이야기\n다음 줄',thoughts:'내 생각',recommendation_rating:4,recommendation_reason:'추천하는 까닭',status:'approved',author_nickname:'친구 '+i,mine:false}))});await f.locator('[data-shelf-scope=class]').click();await f.waitForFunction(()=>document.querySelectorAll('.shelf-book').length===20);assert.equal(await f.locator('#shelfRows img').count(),0);assert.equal(await f.evaluate(()=>window.shelfXss),undefined);await f.locator('[data-shelf-more]').click();await f.waitForFunction(()=>document.querySelectorAll('.shelf-book').length===23);assert(await f.locator('[data-shelf-more]').isHidden());
 await f.locator('[data-shelf-scope=mine]').click();await f.locator('[data-shelf-edit]').click();assert(await f.locator('#readingEntryForm').isVisible());assert.equal(await f.locator('#readingFormTitle').textContent(),'선생님 말씀을 읽고 다듬기');assert.equal(await f.locator('#readingBookTitle').inputValue(),'구름 학교');await page.keyboard.press('Escape');await f.locator('[data-place=reading]').click();assert.equal(await f.locator('#readingBookTitle').inputValue(),'구름 학교');await f.locator('#readingNew').click();assert.equal(await f.locator('#readingBookTitle').inputValue(),'내가 쓰던 책');await page.keyboard.press('Escape');
 await f.evaluate(()=>{mockRpg.shelfReviews[0].book_title='숲이 건네는 인사';mockRpg.shelfReviews[0].author_nickname='꽃나래'});for(const [width,height] of [[1366,900],[390,844],[320,640]]){await page.setViewportSize({width,height});await f.locator('[data-place=portfolio]').tap();await f.locator('.shelf-book').first().waitFor();await f.locator('[data-shelf-scope=class]').tap();await f.locator('.shelf-book').first().waitFor();await f.locator('.shelf-book summary').first().focus();await page.keyboard.press('Enter');assert(await f.locator('.shelf-review').first().isVisible());assert(await f.locator('#readingShelf').evaluate(el=>el.scrollWidth<=el.clientWidth+1));for(const b of await f.locator('#readingShelf button').all()){if(!await b.isVisible())continue;const r=await b.boundingBox();assert(r.height>=44&&r.width>=44)}await page.screenshot({path:path.join(shots,'reading-shelf-'+width+'.png'),fullPage:true});await page.keyboard.press('Escape')}
 await f.evaluate(()=>mockRpg.failShelf=true);await f.locator('[data-place=portfolio]').click();await f.locator('[data-shelf-retry]').waitFor();await f.evaluate(()=>mockRpg.failShelf=false);await f.locator('[data-shelf-retry]').click();await f.locator('.shelf-book').first().waitFor();await f.locator('[data-shelf-write]').click();assert(await f.locator('#readingEntryForm').isVisible());await page.keyboard.press('Escape');
 await f.evaluate(()=>{const rpc=db.rpc.bind(db);db.rpc=async(name,args)=>{const result=await rpc(name,args);if(name==='student_reading_shelf')return new Promise(r=>window.shelfReply=()=>r(result));return result}});await f.locator('[data-place=portfolio]').click();await f.waitForFunction(()=>window.shelfReply);await f.evaluate(()=>{mockRpg.student.id=988;document.dispatchEvent(new Event('student-dashboard-updated'));mockRpg.student.id=987;document.dispatchEvent(new Event('student-dashboard-updated'));shelfReply()});await page.waitForTimeout(100);assert(!await f.locator('#readingShelf').isVisible());assert.equal(await f.locator('.shelf-book').count(),0);assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold]),[260,180]);assert.deepEqual(errors,[]);console.log('PASS: separate desk/shelf, own/class tabs, safe text/read details, bounded pagination, own revision and draft preservation, retry/write link, keyboard/touch/1366/390/320, stale account isolation and unchanged economy.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
