const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1366,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);const f=page.frames().find(f=>f.url().includes('app-core.html'));await f.waitForFunction(()=>window.studentCampus);await f.evaluate(()=>{mockRpg.student.xp=3155;dispatchEvent(new CustomEvent('student-dashboard-updated'))});fs.mkdirSync(shots,{recursive:true});
 for(const room of ['classroom','hallway','library','garden','playground','pond','cafeteria']){await f.evaluate(()=>studentAdventure.map());await f.locator('.sa-map-pin[data-chapter='+room+']').click();await f.waitForFunction(room=>document.getElementById('classroomHub').dataset.scene===room,room);assert(!await f.locator('#saDialog').isVisible());await f.locator('.campus-scene-status').waitFor({state:'hidden'});assert(await f.locator('[data-route=story]').isVisible());}
 for(const [width,height] of [[1366,768],[700,900],[390,844],[320,640]]){await page.setViewportSize({width,height});for(const room of ['garden','playground','pond','cafeteria']){await f.evaluate(room=>enterHubScene(room),room);await f.locator('.campus-scene-status').waitFor({state:'hidden'});await f.waitForTimeout(180);const before=await f.locator('.hub-stage').evaluate(el=>({x:el.getBoundingClientRect().x,w:el.clientWidth,view:el.parentElement.clientWidth}));assert(before.w>before.view+100);await f.locator('#campusTitle').focus();await page.keyboard.down('ArrowRight');await f.waitForFunction(()=>parseFloat(document.getElementById('hubPlayer').style.left)>=51,undefined,{timeout:10000});await page.keyboard.up('ArrowRight');assert(await f.locator('.hub-stage').evaluate((el,x)=>el.getBoundingClientRect().x<x-30,before.x),'Camera follows walking right '+width+' '+room+' '+JSON.stringify(await f.evaluate(()=>({x:document.getElementById("hubPlayer").style.left,dialogs:[...document.querySelectorAll("dialog[open]")].map(e=>e.id),transform:document.querySelector(".hub-stage").style.transform}))));assert(await f.locator('[data-campus=use]').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight+1));assert(await f.locator('#classroomHub').evaluate(el=>el.scrollWidth<=innerWidth+1));await f.locator('[data-place=look-1]').click();assert(await f.locator('#campusGuide').isVisible());assert(await f.locator('.campus-guide-choices').isHidden());await page.keyboard.press('Escape');await f.locator('[data-route=story]').click();assert(await f.locator('#saQuestion').isVisible());await page.keyboard.press('Escape');if(room==='garden')await page.screenshot({path:path.join(shots,'world-garden-'+width+'.png'),fullPage:true});}}
 await page.setViewportSize({width:390,height:844});await f.evaluate(()=>enterHubScene('classroom'));await f.locator('[data-place=quests]').tap();assert.equal(await f.locator('#campusNpcName').textContent(),'담임선생님');await page.keyboard.press('Escape');await f.evaluate(()=>enterHubScene('library'));await f.locator('[data-place=tori]').tap();assert(await f.locator('.campus-guide-choices').isVisible());assert.match(await f.locator('#campusGuideTitle').textContent(),/토리/);for(const b of await f.locator('.campus-guide-choices button').all()){const r=await b.boundingBox();assert(r.height>=44&&r.width>=44)}await page.screenshot({path:path.join(shots,'world-tori-390.png'),fullPage:true});await page.keyboard.press('Escape');
 assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold]),[3155,180]);assert.deepEqual(errors,[]);console.log('PASS: seven map entries lead to walking, four original wide scenes, right-follow camera, object/story interactions, desktop/tablet/390/320 controls, teacher rename and Tori touch dialogue, unchanged economy.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
