const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {chromium}=require('playwright');const {server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'}),base='http://127.0.0.1:'+server.address().port;
try{const page=await browser.newPage({viewport:{width:1366,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto(base);let f=page.frames().find(f=>f.url().includes('app-core.html'));
const ready=()=>f.waitForFunction(()=>window.studentAdventure?.finale&&window.studentCampus&&document.getElementById('saProfileTitle')?.textContent.includes('별나래'));await ready();
const xp=async n=>{await f.evaluate(n=>mockRpg.student.xp=n,n);await page.waitForTimeout(550);await f.evaluate(()=>loadDashboard());await f.waitForFunction(n=>document.querySelector('#saProfileProgress .sa-currency')?.textContent.includes(n+' 경험치'),n)};
const open=()=>f.evaluate(()=>studentAdventure.workshop('school-finale')),close=()=>f.locator('[data-final=close]').first().click();
await xp(1819);await f.evaluate(()=>enterHubScene('classroom'));await f.locator('[data-place=quests]').click();await f.locator('[data-npc-action=finale]').click();await f.waitForFunction(()=>document.getElementById('schoolFinaleDialog')?.textContent.includes('Lv.20에'));assert.match(await f.locator('#schoolFinaleDialog').textContent(),/Lv.20에/);assert.equal(await f.locator('[data-final-slot]').count(),0);await close();
await xp(1820);await open();assert.equal(await f.locator('[data-final-visit]').count(),5);await f.locator('[data-final=save]').click();assert.equal(await f.evaluate(()=>mockRpg.finaleSaves||0),0);await f.locator('[data-final-visit=letter]').click();await f.locator('#gardenLetterDialog').waitFor();await f.locator('[data-letter=close]').first().click();
await f.evaluate(()=>{mockRpg.exploration=['music-sequence-3','parcel-3','letter-3'];localStorage.setItem('fixtureExploration',JSON.stringify(mockRpg.exploration))});await open();assert.equal(await f.locator('[data-final-memory]').count(),3);assert.equal(await f.locator('[data-final-visit]').count(),2);
const from=await f.locator('[data-final-memory=melody]').boundingBox(),to=await f.locator('[data-final-slot="0"]').boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:12});await page.mouse.up();assert.match(await f.locator('[data-final-slot="0"]').textContent(),/멜로디/);
for(const [i,id]of [[1,'parcel'],[2,'letter']]){await f.locator('[data-final-memory='+id+']').focus();await page.keyboard.press('Enter');await f.locator('[data-final-slot="'+i+'"]').focus();await page.keyboard.press('Enter')}
await f.locator('[data-final-ribbon=sunset]').click();assert.equal(await f.locator('#finaleBoard .finale-cord').getAttribute('data-ribbon'),'sunset');fs.mkdirSync(shots,{recursive:true});
for(const [width,height]of [[1366,768],[390,844],[320,640]]){await page.setViewportSize({width,height});await f.locator('#schoolFinaleDialog').evaluate(d=>d.scrollTop=0);assert(!await f.locator('#schoolFinaleDialog').evaluate(d=>d.scrollWidth>d.clientWidth+1));for(const b of await f.locator('[data-final-slot]').all()){const box=await b.boundingBox();assert(box.width>=44&&box.height>=44)}await page.screenshot({path:path.join(shots,'finale-workbench-'+width+'.png'),fullPage:true})}
await close();await page.reload();f=page.frames().find(f=>f.url().includes('app-core.html'));await ready();await xp(1820);await open();assert.match(await f.locator('#finaleStatus').textContent(),/꾸미던/);assert.match(await f.locator('[data-final-slot="2"]').textContent(),/초록 편지/);
await f.evaluate(()=>mockRpg.failFinale=true);await f.locator('[data-final=save]').click();await f.waitForFunction(()=>document.getElementById('finaleStatus')?.textContent.includes('연결'));assert.equal(await f.locator('#finaleBoard .finale-cord').getAttribute('data-ribbon'),'sunset');
await f.evaluate(()=>{mockRpg.failFinale=false;mockRpg.dropFinaleReply=true});await f.locator('[data-final=save]').click();await f.waitForFunction(()=>document.getElementById('finaleStatus')?.textContent.includes('연결'));const first=await f.evaluate(()=>mockRpg.finale.completed_at);assert(first);await f.evaluate(()=>mockRpg.finaleDelay=300);const saves=await f.evaluate(()=>mockRpg.finaleSaves);await f.locator('[data-final=save]').evaluate(b=>{b.click();b.click()});await page.keyboard.press('Escape');assert(await f.locator('#schoolFinaleDialog').isVisible());await f.locator('.finale-award').waitFor();assert.equal(await f.evaluate(()=>mockRpg.finaleSaves),saves+1);assert.equal(await f.evaluate(()=>mockRpg.finale.completed_at),first);
await f.locator('[data-final=wear]').click();await f.waitForFunction(()=>document.getElementById('finaleStatus')?.textContent.includes('착용'));assert.equal(await f.locator('.finale-profile').count(),0);await f.locator('[data-final=wear]').click();await f.locator('.finale-profile').waitFor({state:'attached'});await close();
await f.evaluate(()=>enterHubScene('classroom'));await f.locator('.finale-world').waitFor();assert.equal(await f.locator('.finale-world i').count(),3);assert.equal(await f.locator('.finale-world').evaluate(el=>getComputedStyle(el).pointerEvents),'none');await f.locator('[data-place=quests]').click();assert.match(await f.locator('.npc-conversation').textContent(),/가랜드를 보았어/);await f.locator('[data-npc-close]').first().click();
for(const [width,height]of [[1366,768],[390,844],[320,640]]){await page.setViewportSize({width,height});await f.evaluate(()=>enterHubScene('classroom'));assert(!await f.locator('#classroomHub').evaluate(d=>d.scrollWidth>d.clientWidth+1));await page.screenshot({path:path.join(shots,'finale-classroom-'+width+'.png'),fullPage:true})}await f.evaluate(()=>enterHubScene('library'));assert(await f.locator('.finale-world').isHidden());
await page.reload();f=page.frames().find(f=>f.url().includes('app-core.html'));await ready();await xp(0);await open();assert(await f.locator('.finale-award').isVisible());await page.screenshot({path:path.join(shots,'finale-memory-320.png'),fullPage:true});await f.locator('[data-final=edit]').click();await f.locator('[data-final-ribbon=sky]').click();await f.locator('[data-final=save]').click();await f.locator('.finale-award[data-ribbon=sky]').waitFor();assert.equal(await f.evaluate(()=>mockRpg.finale.completed_at),first);assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold,mockRpg.exploration.length]),[0,180,3]);await close();await f.evaluate(()=>openAdventureMap());assert.match(await f.locator('.sa-passport').textContent(),/0 \/ 7/);await f.locator('#studentAdventureDialog [data-sa=close]').click();
// Storage failure leaves remote saving usable.
await open();await f.locator('[data-final=edit]').click();await f.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(k.includes('school-finale-draft'))throw Error('full');return originalSetItem.call(this,k,v)}});await f.locator('[data-final-ribbon=meadow]').click();assert.match(await f.locator('#finaleStatus').textContent(),/임시저장/);await f.locator('[data-final=save]').click();await f.locator('.finale-award[data-ribbon=meadow]').waitFor();await f.evaluate(()=>Storage.prototype.setItem=originalSetItem);
// Native touch and keyboard-equivalent placement at both phone widths, throttled CPU.
for(const width of [390,320]){const touch=await browser.newPage({viewport:{width,height:844},isMobile:true,hasTouch:true});await touch.route('https://**',r=>r.abort());await touch.emulateMedia({reducedMotion:'reduce'});await (await touch.context().newCDPSession(touch)).send('Emulation.setCPUThrottlingRate',{rate:4});await touch.goto(base);const t=touch.frames().find(f=>f.url().includes('app-core.html'));await t.waitForFunction(()=>window.studentAdventure?.finale);await t.evaluate(async()=>{mockRpg.student.xp=1820;mockRpg.exploration=['music-sequence-3','parcel-3','letter-3'];await loadDashboard();await studentAdventure.workshop('school-finale')});for(const [i,id]of ['letter','parcel','melody'].entries()){await t.locator('[data-final-memory='+id+']').tap();await t.locator('[data-final-slot="'+i+'"]').tap()}await t.locator('[data-final-ribbon=sky]').tap();await t.locator('[data-final=save]').tap();await t.locator('.finale-award').waitFor();assert(!await t.locator('#schoolFinaleDialog').evaluate(d=>d.scrollWidth>d.clientWidth+1));await touch.close()}
assert.deepEqual(errors,[]);console.log('PASS: Lv20/NPC gate, 3-of-5 earned memories, unfinished-story links, actual drag/touch/keyboard, draft/reload/storage failure, error/lost response/duplicate submit, wear/redecorate/XP correction, profile/world/teacher memory, unchanged economy/stamps, 1366/390/320 and slow CPU');
}finally{await browser.close();server.closeAllConnections();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
