const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const picture=['empty','red','empty','red','empty',...Array(10).fill('red'),'empty','red','red','red','empty','empty','empty','red','empty','empty'];const page=await browser.newPage({viewport:{width:1366,height:900},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);let f=page.frames().find(f=>f.url().includes('app-core.html'));await f.waitForFunction(()=>window.studentAdventure);fs.mkdirSync(shots,{recursive:true});
 const xp=async n=>{await f.evaluate(n=>mockRpg.student.xp=n,n);await page.waitForTimeout(550);await f.evaluate(()=>loadDashboard())},launch=async()=>{await f.evaluate(()=>studentAdventure.map(true));await f.locator('[data-workshop=art-frame]').waitFor({state:'attached'});if(await f.locator('[data-map-tab=notebook]').isVisible())await f.locator('[data-map-tab=notebook]').click();await f.locator('[data-workshop=art-frame]').click()},close=()=>f.locator('#studentAdventureDialog [data-sa=close]').click();
 await xp(1584);await launch();assert.match(await f.locator('#saDialogSubtitle').textContent(),/Lv. 18/);await close();await xp(1585);await launch();assert.equal(await f.locator('[data-workshop=art-postcard]').count(),1);assert.equal(await f.locator('#framePreview').count(),0);await close();
 await f.evaluate(picture=>{mockRpg.art={...mockRpg.art,phase:2,cells:picture,stamp:'heart'};localStorage.setItem('fixtureArt',JSON.stringify(mockRpg.art))},picture);await launch();await f.locator('[data-frame-background=night]').click();await f.locator('[data-frame-frame=star]').click();assert.equal(await f.locator('#framePreview').getAttribute('data-background'),'night');
 const flower=await f.locator('[data-frame-ornament=flower]').boundingBox(),slot=await f.locator('[data-frame-slot=top-left]').boundingBox();await page.mouse.move(flower.x+flower.width/2,flower.y+flower.height/2);await page.mouse.down();await page.mouse.move(slot.x+slot.width/2,slot.y+slot.height/2,{steps:14});await page.mouse.up();assert.match(await f.locator('[data-frame-slot=top-left]').getAttribute('aria-label'),/꽃/);await close();await launch();assert.equal(await f.locator('#framePreview').getAttribute('data-background'),'night');assert.match(await f.locator('#frameStatus').textContent(),/이어|다시/);
 await f.evaluate(()=>{const set=Storage.prototype.setItem;window.restoreStorage=()=>Storage.prototype.setItem=set;Storage.prototype.setItem=function(k,v){if(k.includes('art-frame-draft'))throw Error('storage unavailable');return set.call(this,k,v)}});await f.locator('[data-frame-background=meadow]').click();assert.match(await f.locator('#frameStatus').textContent(),/임시저장하지 못/);await f.locator('[data-frame-background=night]').click();await f.evaluate(()=>restoreStorage());await f.evaluate(()=>mockRpg.failFrame=true);await f.locator('[data-frame-save]').click();assert.match(await f.locator('#frameFeedback').textContent(),/확인하지 못/);assert.equal(await f.locator('#framePreview').getAttribute('data-background'),'night');await f.evaluate(()=>{mockRpg.failFrame=false;mockRpg.loseFrameReply=true});await f.locator('[data-frame-save]').click();assert.match(await f.locator('#frameFeedback').textContent(),/확인하지 못/);await f.locator('[data-frame-save]').dblclick();assert.match(await f.locator('#frameFeedback').textContent(),/저장했어요/);const first=await f.evaluate(()=>mockRpg.art.decorated_at);assert(first);
 await page.reload();f=page.frames().find(f=>f.url().includes('app-core.html'));await f.waitForFunction(()=>window.studentAdventure);await xp(0);await launch();assert.equal(await f.locator('#framePreview').getAttribute('data-frame'),'star');assert.match(await f.locator('[data-frame-slot=top-left]').getAttribute('aria-label'),/꽃/);await f.locator('[data-frame-background=sunset]').click();await f.locator('[data-frame-save]').click();assert.equal(await f.evaluate(()=>mockRpg.art.decorated_at),first);assert.deepEqual(await f.evaluate(()=>mockRpg.art.cells),picture);assert.equal(await f.evaluate(()=>mockRpg.art.stamp),'heart');
 for(const [width,height] of [[1366,900],[390,844],[320,640]]){await page.setViewportSize({width,height});await f.locator('[data-frame-background=meadow]').tap();await f.locator('[data-frame-ornament=leaf]').tap();await f.locator('[data-frame-slot=top-right]').tap();assert.match(await f.locator('[data-frame-slot=top-right]').getAttribute('aria-label'),/잎/);assert(await f.locator('#studentAdventureDialog').evaluate(el=>el.scrollWidth<=el.clientWidth+1));for(const b of await f.locator('[data-frame-slot],[data-frame-ornament],[data-frame-background],[data-frame-frame]').all()){const r=await b.boundingBox();assert(r.width>=44&&r.height>=44)}await f.locator('#framePreview').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(shots,'frame-'+width+'.png'),fullPage:true});}
 await f.locator('[data-frame-slot=top-right]').focus();await page.keyboard.press('Enter');assert.match(await f.locator('[data-frame-slot=top-right]').getAttribute('aria-label'),/잎/);await f.locator('[data-frame-reset]').click();assert.equal(await f.locator('#framePreview').getAttribute('data-background'),'sunset');
 await f.evaluate(()=>{const rpc=db.rpc.bind(db);db.rpc=async(name,args)=>{const result=await rpc(name,args);if(name==='student_art_frame')return new Promise(r=>window.frameReply=()=>r(result));return result}});await f.locator('[data-frame-save]').click();await f.waitForFunction(()=>window.frameReply);await page.keyboard.press('Escape');assert(await f.locator('#studentAdventureDialog').isVisible());await f.evaluate(()=>{mockRpg.student.id=988;document.dispatchEvent(new Event('student-dashboard-updated'));mockRpg.student.id=987;mockRpg.art={phase:2,cells:Array(25).fill('red'),stamp:'leaf',background:'cream',frame:'wood',ornament:'none',placement:'bottom-right',decorated_at:null};document.dispatchEvent(new Event('student-dashboard-updated'));frameReply()});await page.waitForTimeout(100);assert(!await f.locator('#studentAdventureDialog').isVisible());
 assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold]),[0,180]);assert.deepEqual(errors,[]);console.log('PASS: Lv18 gate/prerequisite, live background/frame preview, actual sticker drag/touch/keyboard, draft/reload/XP correction, failure/lost response/edit timestamp, picture invariants, A-B-A delayed-save guard and 1366/390/320 layouts.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
