begin;
do $test$
declare sid bigint;other_sid bigint;t text:=gen_random_uuid()::text;t2 text:=gen_random_uuid()::text;blocked boolean;r jsonb;old jsonb;first_at text;picture text[]:=array_fill('green'::text,array[25]);
begin
 select id into sid from public.students order by id limit 1;select id into other_sid from public.students where id<>sid order by id limit 1;
 delete from rpg_private.school_art where student_id in(sid,other_sid);
 update public.students set xp=1584,session_hash=encode(extensions.digest(convert_to(t,'UTF8'),'sha256'),'hex'),session_expires_at=now()+interval '1 hour' where id=sid;
 update public.students set xp=1585,session_hash=encode(extensions.digest(convert_to(t2,'UTF8'),'sha256'),'hex'),session_expires_at=now()+interval '1 hour' where id=other_sid;
 old:=jsonb_build_object('gold',(select gold from public.students where id=sid),'items',(select count(*) from public.student_items where student_id=sid),'stamps',(select count(*) from rpg_private.school_exploration where student_id=sid));
 blocked:=false;begin perform public.student_art_frame('invalid','cream','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Invalid token';end if;
 blocked:=false;begin perform public.student_art_frame(null,'cream','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Null token';end if;
 blocked:=false;begin perform public.student_art_frame(t2,'cream','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Missing picture';end if;
 perform public.student_art_postcard(t,'mix',array['blue','yellow']);
 blocked:=false;begin perform public.student_art_frame(t,'cream','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Incomplete picture';end if;
 perform public.student_art_postcard(t,'save',picture,'heart');
 blocked:=false;begin perform public.student_art_frame(t,'cream','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Lv17 bypass';end if;
 update public.students set xp=1585 where id=sid;
 blocked:=false;begin perform public.student_art_frame(t,null,'wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Null background';end if;
 blocked:=false;begin perform public.student_art_frame(t,'invented','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Unknown background';end if;
 blocked:=false;begin perform public.student_art_frame(t,'cream','invented','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Unknown frame';end if;
 blocked:=false;begin perform public.student_art_frame(t,'cream','wood','invented','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Unknown ornament';end if;
 blocked:=false;begin perform public.student_art_frame(t,'cream','wood','leaf','invented');exception when others then blocked:=true;end;if not blocked then raise exception 'Unknown placement';end if;
 update public.students set session_expires_at=now()-interval '1 second' where id=sid;
 blocked:=false;begin perform public.student_art_frame(t,'cream','wood','leaf','top-left');exception when others then blocked:=true;end;if not blocked then raise exception 'Expired token';end if;
 update public.students set session_expires_at=now()+interval '1 hour' where id=sid;
 r:=public.student_art_frame(t,'night','star','flower','top-left');first_at:=r->>'decorated_at';if first_at is null or r->>'background'<>'night' then raise exception 'Missing frame result';end if;
 r:=public.student_art_frame(t,'night','star','flower','top-left');if r->>'decorated_at'<>first_at then raise exception 'Replay timestamp';end if;
 if public.student_learning_journal(t2)->'art'->>'decorated_at' is not null then raise exception 'Other student frame leaked';end if;
 update public.students set xp=0 where id=sid;r:=public.student_art_frame(t,'sunset','leaf','none','bottom-right');if r->>'decorated_at'<>first_at then raise exception 'XP correction/timestamp';end if;
 if r->'cells'<>to_jsonb(picture) or r->>'stamp'<>'heart' then raise exception 'Picture changed by frame';end if;
 perform public.student_art_postcard(t,'save',picture,'star');r:=public.student_learning_journal(t)->'art';if r->>'background'<>'sunset' or r->>'frame'<>'leaf' or r->>'decorated_at'<>first_at then raise exception 'Picture edit erased frame';end if;
 if old<>jsonb_build_object('gold',(select gold from public.students where id=sid),'items',(select count(*) from public.student_items where student_id=sid),'stamps',(select count(*) from rpg_private.school_exploration where student_id=sid)) then raise exception 'Economy changed';end if;
 if (select xp from public.students where id=sid)<>0 then raise exception 'Frame writes XP';end if;
 if has_function_privilege('anon','rpg_private.art_state(bigint)','execute') or has_table_privilege('anon','rpg_private.school_art','select') or has_function_privilege('authenticated','rpg_private.art_state(bigint)','execute') or has_table_privilege('authenticated','rpg_private.school_art','update') then raise exception 'Private access allowed';end if;
 if not has_function_privilege('anon','public.student_art_frame(text,text,text,text,text)','execute') or not has_function_privilege('authenticated','public.student_art_frame(text,text,text,text,text)','execute') then raise exception 'Missing intended RPC grants';end if;
 perform set_config('rpg.frame_test_token',t,true);
end $test$;
set local role anon;
do $roles$ declare blocked boolean:=false;begin
 if (public.student_art_frame(current_setting('rpg.frame_test_token'),'meadow','wood','leaf','top-right')->>'background')<>'meadow' then raise exception 'Anon RPC failed';end if;
 begin perform 1 from rpg_private.school_art;exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Anon private table';end if;
 blocked:=false;begin perform rpg_private.art_state(1);exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'Anon private helper';end if;
end $roles$;
reset role;
set local role authenticated;
do $roles$ begin if (public.student_art_frame(current_setting('rpg.frame_test_token'),'meadow','wood','none','top-right')->>'ornament')<>'none' then raise exception 'Authenticated RPC failed';end if;end $roles$;
reset role;
rollback;
select 'PASS: Lv18 boundary, prerequisites, token/null/expiry, style validation, owner isolation, replay/edit/XP correction, picture and economy invariants, private access and RPC grants' as result;
