const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);let f;
 const ready=async()=>{f=page.frames().find(f=>f.url().includes('app-core'));await f.waitForFunction(()=>window.studentCampus?.parcel&&document.getElementById('saProfileTitle')?.textContent.includes(mockRpg.student.nickname));await f.evaluate(()=>enterHubScene('library'));await f.locator('.campus-scene-status').waitFor({state:'hidden'})};await ready();
 assert.equal(await f.locator('.campus-story-bubble').count(),0);await f.locator('[data-place=tori]').click();assert.match(await f.locator('#campusGuideTitle').textContent(),/토리/);await f.locator('[data-guide=close]').first().click();
 await f.evaluate(()=>localStorage.setItem('fixtureExploration',JSON.stringify(['parcel-1','parcel-2'])));await page.reload();await ready();await f.locator('[data-place=tori][data-parcel-story=delivery]').waitFor();await f.locator('[data-place=tori]').click();assert.match(await f.locator('#campusGuideTitle').textContent(),/꾸러미를 찾았/);assert.match(await f.locator('[data-guide=parcel]').textContent(),/전해 주기/);await f.locator('[data-guide=parcel]').click();await f.locator('[data-parcel-save=parcel-3]').click();await f.locator('[data-parcel-next]').waitFor();await f.locator('[data-parcel-close]').click();
 await f.locator('[data-place=tori][data-parcel-story=complete]').waitFor();assert.match(await f.locator('.campus-story-bubble').textContent(),/준비 완료/);const requests=await f.evaluate(()=>mockRpg.calls.filter(x=>x==='student_learning_journal').length);fs.mkdirSync(shots,{recursive:true});
 for(const [width,height] of [[1366,768],[390,844],[320,640]]){
  await page.setViewportSize({width,height});await f.locator('[data-place=tori]').focus();await f.waitForFunction(()=>document.querySelector('.hub-stage').getAnimations().every(a=>a.playState!=='running'));await page.screenshot({path:path.join(shots,'story-tori-world-'+width+'.png'),fullPage:true});
  await (width<=390?f.locator('[data-place=tori]').tap():f.locator('[data-place=tori]').click());assert.match(await f.locator('#campusGuideTitle').textContent(),/다시 와 줬구나/);assert.match(await f.locator('.campus-greeting p').textContent(),/책 나눔 준비를 마쳤어/);assert.equal(await f.locator('#campusGuide').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);await page.screenshot({path:path.join(shots,'story-tori-dialog-'+width+'.png'),fullPage:true});await f.locator('[data-guide=close]').first().click();
  const bubble=await f.locator('.campus-story-bubble').boundingBox();assert(bubble.x>=-1&&bubble.x+bubble.width<=width+1,'NPC reaction fits the focused mobile view');assert.equal(await f.locator('.campus-story-bubble').evaluate(el=>getComputedStyle(el).pointerEvents),'none');
  assert(await f.locator('.campus-story-bubble').evaluate(el=>{const r=el.getBoundingClientRect();return [...document.querySelectorAll('[data-place]:not([data-place=tori]) .campus-object-caption')].every(label=>{const b=label.getBoundingClientRect();return r.right<=b.left||r.left>=b.right||r.bottom<=b.top||r.top>=b.bottom})}),'The reaction must not cover another object name');
  assert(await f.locator('[data-campus=use]').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight+1));
 }
 assert.equal(await f.evaluate(()=>mockRpg.calls.filter(x=>x==='student_learning_journal').length),requests,'NPC reactions reuse confirmed progress without extra requests');
 await page.reload();await ready();await f.locator('[data-place=tori][data-parcel-story=complete]').waitFor();
 await f.evaluate(()=>{const rpc=db.rpc.bind(db);window.journalReplies=[];db.rpc=async(name,args)=>{const result=await rpc(name,args);if(name==='student_learning_journal'&&window.holdJournal){const frozen=structuredClone(result);return new Promise(resolve=>journalReplies.push(()=>resolve(frozen)))}return result}});
 const account=async(id,steps,{hold=false,fail=false}={})=>f.evaluate(({id,steps,hold,fail})=>{mockRpg.student.id=id;mockRpg.exploration=steps;mockRpg.failJournal=fail;window.holdJournal=hold;document.dispatchEvent(new Event('student-dashboard-updated'));enterHubScene('library')},{id,steps,hold,fail});
 await account(988,[],{fail:true});await f.locator('[data-place=tori]').waitFor();assert.equal(await f.locator('.campus-story-bubble').count(),0);await f.locator('[data-place=tori]').tap();assert.match(await f.locator('#campusGuideTitle').textContent(),/토리/);await f.locator('[data-guide=close]').first().click();
 await account(989,['parcel-1','parcel-2'],{hold:true});await f.locator('.parcel-tracker').tap();await f.waitForFunction(()=>journalReplies.length>0);await page.keyboard.press('Escape');assert(!await f.locator('#parcelAdventureDialog').isVisible());await f.evaluate(()=>journalReplies.splice(0).forEach(release=>release()));await page.waitForTimeout(100);assert(!await f.locator('#parcelAdventureDialog').isVisible(),'A late load must not reopen a closed conversation');
 await account(990,['parcel-1','parcel-2'],{hold:true});await f.locator('[data-place=tori]').tap();await f.locator('[data-guide=parcel]').tap();await f.locator('[data-parcel-close]').waitFor();await f.locator('[data-parcel-close]').tap();await f.locator('.parcel-tracker').tap();await f.evaluate(()=>journalReplies.splice(0).forEach(release=>release()));await f.locator('[data-parcel-go]').waitFor();await f.locator('[data-parcel-close]').click();
 // Return to the same ID before an older request finishes: generation must win over ID alone.
 await account(995,[],{hold:true});await f.waitForFunction(()=>journalReplies.length>0);await account(996,[],{hold:true});await account(995,['parcel-1','parcel-2','parcel-3']);await f.evaluate(()=>enterHubScene('library'));await f.locator('[data-place=tori][data-parcel-story=complete]').waitFor();await f.evaluate(()=>journalReplies.splice(0).forEach(release=>release()));await page.waitForTimeout(100);assert.equal(await f.locator('[data-place=tori]').getAttribute('data-parcel-story'),'complete');
 await f.locator('.parcel-tracker').tap();await account(997,[],{fail:true});assert(!await f.locator('#parcelAdventureDialog').isVisible(),'Account switch closes the previous student conversation');assert.equal(await f.locator('.campus-story-bubble').count(),0);
 await f.evaluate(()=>{const rpc=db.rpc.bind(db);window.saveReplies=[];db.rpc=async(name,args)=>{const result=await rpc(name,args);if(name==='student_parcel_adventure')return new Promise(resolve=>saveReplies.push(()=>resolve(result)));return result}});
 await account(999,['parcel-1','parcel-2']);await f.locator('[data-place=tori][data-parcel-story=delivery]').waitFor();await f.locator('[data-place=tori]').tap();await f.locator('[data-guide=parcel]').tap();await f.locator('[data-parcel-save=parcel-3]').tap();await f.waitForFunction(()=>saveReplies.length>0);await account(1000,[]);await account(999,['parcel-1']);await f.locator('.parcel-tracker').tap();await f.locator('[data-parcel-go=hallway]').waitFor();await f.evaluate(()=>saveReplies.splice(0).forEach(release=>release()));await page.waitForTimeout(100);assert.equal(await f.locator('.campus-story-bubble').count(),0);assert.match(await f.locator('.parcel-tracker').textContent(),/복도의 도서 안내판/);await f.locator('[data-parcel-close]').tap();
 const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await account(998,['parcel-1','parcel-2','parcel-3']);await f.evaluate(()=>enterHubScene('library'));await page.emulateMedia({reducedMotion:'reduce'});await f.locator('[data-place=tori][data-parcel-story=complete]').waitFor();await f.locator('[data-place=tori]').focus();await page.keyboard.press('Enter');assert.match(await f.locator('#campusGuideTitle').textContent(),/다시 와/);await page.keyboard.press('Escape');await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
 assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold,mockRpg.parcelSaves]),[260,180,1]);assert.deepEqual(errors,[]);console.log('PASS: server-backed NPC delivery/completion reactions, reload, no extra journal calls/rewards, touch/keyboard/1366/390/320, slow-load close/reopen, account failure and A-B-A stale read/save responses, CPU throttling and reduced motion.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
