const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);let f;
 const ready=async()=>{f=page.frames().find(f=>f.url().includes('app-core'));await f.waitForFunction(()=>window.studentCampus&&document.getElementById('saProfileTitle')?.textContent.includes(mockRpg.student.nickname));await f.evaluate(()=>openClassroomHub());await f.locator('#classroomHub').waitFor()};await ready();
 const spot=()=>f.evaluate(()=>({room:document.getElementById('classroomHub').dataset.scene,x:parseFloat(document.getElementById('hubPlayer').style.left)}));
 const direct=await browser.newPage();await direct.route('https://**',r=>r.abort());await direct.goto('http://127.0.0.1:'+server.address().port);const df=direct.frames().find(f=>f.url().includes('app-core'));await df.waitForFunction(()=>window.studentCampus&&document.getElementById('saProfileTitle')?.textContent.includes(mockRpg.student.nickname));
 await df.evaluate(()=>{localStorage.setItem('classRpgCampusSpot_v1_987',JSON.stringify({v:1,room:'hallway',x:60}));enterHubScene('library')});await df.locator('#classroomHub[data-scene=library]').waitFor();assert.equal(await df.locator('#classroomHub').getAttribute('data-scene'),'library','Explicit quest/room entry wins over the saved room');await direct.close();
 await f.evaluate(()=>enterHubScene('library'));await f.evaluate(()=>{for(let i=0;i<4;i++)moveHub(1,0)});await f.waitForFunction(()=>JSON.parse(localStorage.getItem('classRpgCampusSpot_v1_987')||'null')?.x===48);
 await page.reload();await ready();await f.waitForFunction(()=>document.getElementById('classroomHub').dataset.scene==='library'&&parseFloat(document.getElementById('hubPlayer').style.left)===48);assert.deepEqual(await spot(),{room:'library',x:48});
 await f.evaluate(()=>closeClassroomHub());await f.evaluate(()=>openClassroomHub());assert.deepEqual(await spot(),{room:'library',x:48},'Returning from the dashboard resumes the same walk');
 await f.evaluate(async()=>{mockRpg.student.id=988;await loadDashboard()});await f.waitForFunction(()=>document.getElementById('classroomHub').dataset.scene==='classroom');assert.equal((await spot()).x,44);
 await f.evaluate(()=>enterHubScene('hallway'));await f.evaluate(()=>moveHub(1,0));await f.evaluate(async()=>{mockRpg.student.id=987;await loadDashboard()});await f.waitForFunction(()=>document.getElementById('classroomHub').dataset.scene==='library');assert.equal((await spot()).x,48);assert.deepEqual(await f.evaluate(()=>JSON.parse(localStorage.getItem('classRpgCampusSpot_v1_988'))),{v:1,room:'hallway',x:47});
 await f.evaluate(()=>{moveHub(-1,0);window.dispatchEvent(new Event('pagehide'))});assert.equal(await f.evaluate(()=>JSON.parse(localStorage.getItem('classRpgCampusSpot_v1_987')).x),45,'Page exit flushes the pending location');
 await f.evaluate(()=>closeClassroomHub());await f.evaluate(()=>localStorage.setItem('classRpgCampusSpot_v1_987','{"v":1,"room":"unreleased","x":90}'));await page.reload();await ready();assert.deepEqual(await spot(),{room:'classroom',x:44});
 // Storage restrictions are non-fatal and do not change account/quest data.
 await f.evaluate(()=>{const set=localStorage.setItem;localStorage.setItem=(key,value)=>{if(key.startsWith('classRpgCampusSpot_'))throw Error('storage unavailable');return set(key,value)};enterHubScene('library')});await f.evaluate(()=>moveHub(1,0));await page.waitForTimeout(400);assert.deepEqual(await spot(),{room:'library',x:39});
 await page.reload();await ready();fs.mkdirSync(shots,{recursive:true});
 for(const [width,height] of [[1366,768],[390,844],[320,640]]){
  await page.setViewportSize({width,height});await f.evaluate(()=>{enterHubScene('library');enterHubScene('hallway')});await f.locator('.campus-scene-status').waitFor({state:'hidden'});await f.waitForFunction(()=>document.querySelector('.hub-stage').getAnimations().every(a=>a.playState!=='running'));
  const box=await f.locator('.hub-stage').boundingBox();await (width<=390?page.touchscreen.tap(Math.round(box.x+box.width*.62),box.y+box.height*.795):page.mouse.click(Math.round(box.x+box.width*.62),box.y+box.height*.795));await f.locator('.campus-waypoint[data-state=walking]').waitFor();assert.equal(await f.locator('.campus-waypoint').evaluate(el=>getComputedStyle(el).pointerEvents),'none');await page.screenshot({path:path.join(shots,'journey-marker-'+width+'.png'),fullPage:true});
  await f.locator('.campus-waypoint[data-state=arrived]').waitFor();assert(Math.abs((await spot()).x-62)<.2);await f.locator('.campus-waypoint').waitFor({state:'hidden'});
  assert(await f.locator('#classroomHub').evaluate(el=>el.scrollWidth<=el.clientWidth+1));assert(await f.locator('[data-campus=use]').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight+1));
 }
 await f.locator('[data-campus=find]').click();await f.locator('[data-finder-place=library]').click();await f.locator('.campus-waypoint').waitFor();await page.keyboard.press('ArrowLeft');assert(!(await f.locator('.campus-waypoint').isVisible()));
 await page.emulateMedia({reducedMotion:'reduce'});await f.evaluate(()=>{enterHubScene('library');enterHubScene('hallway')});await f.locator('.campus-scene-status').waitFor({state:'hidden'});const box=await f.locator('.hub-stage').boundingBox();await page.mouse.click(Math.round(box.x+box.width*.62),box.y+box.height*.795);assert.equal(await f.locator('.campus-waypoint').getAttribute('data-state'),'arrived');assert.equal(await f.locator('.campus-waypoint svg').evaluate(el=>getComputedStyle(el).animationName),'none');await f.evaluate(()=>enterHubScene('classroom'));assert(!(await f.locator('.campus-waypoint').isVisible()));
 await page.emulateMedia({reducedMotion:'no-preference'});const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setCPUThrottlingRate',{rate:4});await f.evaluate(()=>enterHubScene('hallway'));await f.locator('.campus-scene-status').waitFor({state:'hidden'});await page.waitForTimeout(400);
 await f.evaluate(()=>{window.spotWrites=0;const set=localStorage.setItem;localStorage.setItem=(key,value)=>{if(key.startsWith('classRpgCampusSpot_'))window.spotWrites++;return set(key,value)}});await f.locator('[data-campus=find]').click();await f.locator('[data-finder-place=library]').click();await f.locator('.campus-waypoint[data-state=arrived]').waitFor();await page.waitForTimeout(400);assert.equal((await spot()).x,85);assert((await f.evaluate(()=>spotWrites))<=3,'Walking storage is debounced, not written on every animation frame');await cdp.send('Emulation.setCPUThrottlingRate',{rate:1});
 assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold]),[260,180]);assert.deepEqual(errors,[]);console.log('PASS: per-account local room/position resume, explicit room entry, pending account switch, pagehide flush, invalid data and unavailable storage, destination/arrival/cancel, reduced motion, real touch laptop/390/320 layouts, 4x CPU throttling/debounced storage, no economy changes.');
}finally{await browser.close();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
