const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),{chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'});try{
 const page=await browser.newPage({viewport:{width:1366,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);let f=page.frames().find(x=>x.url().includes('app-core.html'));await f.waitForFunction(()=>window.studentCampus);await f.evaluate(()=>document.fonts.ready);fs.mkdirSync(shots,{recursive:true});
 for(const [width,height] of [[1366,768],[390,844],[320,640]]){
  await page.setViewportSize({width,height});for(const room of ['classroom','hallway','library','garden','pond','playground','cafeteria']){
   await f.evaluate(room=>enterHubScene(room),room);await f.locator('.campus-scene-status').waitFor({state:'hidden'});await page.waitForTimeout(100);
   const ui=await f.locator('#classroomHub').evaluate(e=>{const r=s=>e.querySelector(s).getBoundingClientRect().toJSON();return {view:r('.campus-viewport'),shell:r('.hub-shell'),header:r('.campus-header'),footer:r('.hub-help'),wallet:r('.campus-wallet'),title:r('#campusTitle'),buttons:[...e.querySelectorAll('.campus-header button,.hub-help button')].filter(x=>x.getClientRects().length).map(x=>({text:x.textContent,r:x.getBoundingClientRect().toJSON()})),h:innerHeight,w:innerWidth,overflow:e.scrollWidth>e.clientWidth+1}});
   assert(!ui.overflow,room+' '+width);assert(ui.header.bottom<=ui.view.top+1);assert(ui.footer.top>=ui.view.bottom-1,'Controls stay below the feet');assert(ui.footer.bottom<=ui.h+1,room+' footer outside '+width+' '+JSON.stringify(ui));assert(ui.view.width>=ui.shell.width-10,'No page-like sidebar');
   for(const b of ui.buttons)assert(b.r.width>=44&&b.r.height>=44,b.text+' target');for(let i=0;i<ui.buttons.length;i++)for(const b of ui.buttons.slice(i+1)){const a=ui.buttons[i];assert(Math.min(a.r.right,b.r.right)<=Math.max(a.r.left,b.r.left)+1||Math.min(a.r.bottom,b.r.bottom)<=Math.max(a.r.top,b.r.top)+1,'Controls must not overlap')}
   assert.match(await f.locator('.campus-wallet').textContent(),/Lv\. 5 · 180 G/);await page.screenshot({path:path.join(shots,'hud-'+room+'-'+width+'.png'),fullPage:true});
  }
  await f.locator('[data-campus=find]').tap();assert(await f.locator('#campusWayfinder').isVisible());await page.keyboard.press('Escape');await f.locator('[data-campus=map]').focus();await page.keyboard.press('Enter');assert(await f.locator('#studentAdventureDialog').isVisible());await page.keyboard.press('Escape');await f.locator('[data-campus=home]').tap();assert(await f.locator('#classroomHub').isHidden());await f.evaluate(()=>openClassroomHub());
 }
 // Compact amounts follow confirmed dashboard state; no previous account's balance remains.
 await f.evaluate(async()=>{mockRpg.student.gold=10300;mockRpg.student.xp=3155;await loadDashboard()});assert.equal(await f.locator('.campus-wallet').textContent(),'Lv. 30 · 10,300 G');await f.evaluate(async()=>{mockRpg.student.id=988;mockRpg.student.gold=7;mockRpg.student.xp=0;await loadDashboard()});assert.equal(await f.locator('.campus-wallet').textContent(),'Lv. 1 · 7 G');await f.evaluate(async()=>{mockRpg.student.id=987;mockRpg.student.gold=180;mockRpg.student.xp=260;await loadDashboard()});assert.equal(await f.locator('.campus-wallet').textContent(),'Lv. 5 · 180 G');
 assert.deepEqual(errors,[]);assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold]),[260,180]);console.log('PASS: seven full-width scene frames, no sidebar/control overlap, 44px targets and 1366/390/320 fitting; keyboard/touch map/find/home; confirmed wallet updates and account isolation.');
}finally{await browser.close();server.closeAllConnections();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
