const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {chromium}=require('playwright');const {server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'}),base='http://127.0.0.1:'+server.address().port;
try{const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto(base);let f=page.frames().find(f=>f.url().includes('app-core.html'));
const ready=()=>f.waitForFunction(()=>window.studentCampus?.letter&&document.getElementById('saProfileTitle')?.textContent.includes('별나래'));await ready();
const xp=async n=>{await f.evaluate(n=>mockRpg.student.xp=n,n);await page.waitForTimeout(550);await f.evaluate(()=>loadDashboard());await f.waitForFunction(n=>document.querySelector('#saProfileProgress .sa-currency')?.textContent.includes(n+' 경험치'),n)};
const room=async id=>{await f.evaluate(id=>enterHubScene(id),id);await f.locator('.campus-scene-status').waitFor({state:'hidden'})};
await xp(1699);await room('library');await f.locator('[data-place=tori]').click();await f.locator('[data-guide=letter]').click();assert.match(await f.locator('#gardenLetterDialog').textContent(),/Lv.19에/);assert.equal(await f.locator('[data-clue]').count(),0);await f.locator('[data-letter=close]').first().click();
await xp(1700);await room('garden');await f.locator('[data-place=look-0]').click();await f.locator('[data-guide=letter-garden]').click();await f.locator('[data-letter=observe]').click();assert.match(await f.locator('#letterFeedback').textContent(),/모두/);assert.equal(await f.evaluate(()=>mockRpg.letterSaves||0),0);
for(const id of ['leaf','stem','light'])await f.locator('[data-clue='+id+']').click();assert.match(await f.locator('#letterClues').textContent(),/3 \/ 3/);
fs.mkdirSync(shots,{recursive:true});for(const [width,height]of [[1366,768],[390,844],[320,640]]){await page.setViewportSize({width,height});assert(!await f.locator('#gardenLetterDialog').evaluate(el=>el.scrollWidth>el.clientWidth+1));for(const b of await f.locator('[data-clue]').all()){const box=await b.boundingBox();assert(box.width>=44&&box.height>=44)}await page.screenshot({path:path.join(shots,'letter-observe-'+width+'.png'),fullPage:true})}
await f.evaluate(()=>mockRpg.failLetter=true);await f.locator('[data-letter=observe]').click();await f.waitForFunction(()=>document.getElementById('letterFeedback')?.textContent.includes('연결'));assert.match(await f.locator('#letterClues').textContent(),/3 \/ 3/);
await f.evaluate(()=>{mockRpg.failLetter=false;mockRpg.dropLetterReply=true});await f.locator('[data-letter=observe]').click();await f.waitForFunction(()=>document.getElementById('letterFeedback')?.textContent.includes('연결'));assert.deepEqual(await f.evaluate(()=>mockRpg.exploration),['letter-1']);
await f.evaluate(()=>mockRpg.letterDelay=300);let saves=await f.evaluate(()=>mockRpg.letterSaves);await f.locator('[data-letter=observe]').evaluate(b=>{b.click();b.click()});await page.keyboard.press('Escape');assert(await f.locator('#gardenLetterDialog').isVisible());await f.locator('[data-letter=next]').waitFor();assert.equal(await f.evaluate(()=>mockRpg.letterSaves),saves+1);await f.locator('[data-letter=next]').click();
// A wrong order gives a gentle hint; no progress is saved.
for(const [i,id]of ['grow','light','leaf'].entries()){await f.locator('[data-word='+id+']').click();await f.locator('[data-slot="'+i+'"]').click()}await f.locator('[data-letter=compose]').click();await f.waitForFunction(()=>document.getElementById('letterFeedback')?.textContent.includes('누가'));assert.deepEqual(await f.evaluate(()=>mockRpg.exploration),['letter-1']);await f.locator('[data-letter=clear]').click();
// Actual mouse drag, then native keyboard placement.
await page.setViewportSize({width:1366,height:900});await f.locator('[data-word=leaf]').scrollIntoViewIfNeeded();const from=await f.locator('[data-word=leaf]').boundingBox(),to=await f.locator('[data-slot="0"]').boundingBox();await page.mouse.move(from.x+from.width/2,from.y+from.height/2);await page.mouse.down();await page.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:12});await page.mouse.up();assert.match(await f.locator('[data-slot="0"]').textContent(),/새싹/);
for(const [i,id]of [[1,'light'],[2,'grow']]){await f.locator('[data-word='+id+']').focus();await page.keyboard.press('Enter');await f.locator('[data-slot="'+i+'"]').focus();await page.keyboard.press('Enter')}
for(const [width,height]of [[1366,768],[390,844],[320,640]]){await page.setViewportSize({width,height});assert(!await f.locator('#gardenLetterDialog').evaluate(el=>el.scrollWidth>el.clientWidth+1));await page.screenshot({path:path.join(shots,'letter-compose-'+width+'.png'),fullPage:true})}
await f.locator('[data-letter=compose]').click();await f.locator('[data-letter=next]').waitFor();await f.locator('[data-letter=close]').first().click();await page.reload();f=page.frames().find(f=>f.url().includes('app-core.html'));await ready();await xp(0);await room('library');await f.locator('[data-place=tori]').click();await f.locator('[data-guide=letter]').click();await f.locator('[data-letter=deliver]').click();await f.locator('[data-letter=next]').waitFor();await f.locator('[data-letter=next]').click();assert(await f.locator('.letter-keepsake').isVisible());await page.screenshot({path:path.join(shots,'letter-finish-320.png'),fullPage:true});await f.locator('[data-letter=close]').first().click();await f.locator('[data-place=tori]').click();assert.match(await f.locator('#campusGuide .campus-greeting p').textContent(),/편지를 기억/);await f.locator('[data-guide=close]').first().click();assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold,mockRpg.exploration.length]),[0,180,3]);
await f.evaluate(()=>openAdventureMap());assert.match(await f.locator('.sa-passport').textContent(),/0 \/ 7/);assert.match(await f.locator('[data-workshop=garden-letter]').textContent(),/기억 보기/);await f.locator('[data-workshop=garden-letter]').click();assert(await f.locator('.letter-keepsake').isVisible());
// New identity cannot display the old memento, including an old in-flight reply.
await f.evaluate(()=>{mockRpg.student.id=988;mockRpg.exploration=[];mockRpg.failJournal=true;document.dispatchEvent(new Event('student-dashboard-updated'))});assert(!await f.locator('#gardenLetterDialog').isVisible());await f.evaluate(()=>studentCampus.letter.start());assert.equal(await f.locator('.letter-keepsake').count(),0);await f.locator('[data-letter=close]').first().click();
// Real touch placement on narrow screens, plus reduced-motion/slow CPU.
for(const width of [390,320]){const touch=await browser.newPage({viewport:{width,height:844},hasTouch:true,isMobile:true});await touch.route('https://**',r=>r.abort());await touch.emulateMedia({reducedMotion:'reduce'});await (await touch.context().newCDPSession(touch)).send('Emulation.setCPUThrottlingRate',{rate:4});await touch.goto(base);const t=touch.frames().find(f=>f.url().includes('app-core.html'));await t.waitForFunction(()=>window.studentCampus?.letter);await t.evaluate(async()=>{mockRpg.student.xp=1700;await loadDashboard();enterHubScene('garden')});await t.locator('[data-place=look-0]').tap();await t.locator('[data-guide=letter-garden]').tap();for(const id of ['leaf','stem','light'])await t.locator('[data-clue='+id+']').tap();await t.locator('[data-letter=observe]').tap();await t.locator('[data-letter=next]').tap();for(const [i,id]of ['leaf','light','grow'].entries()){await t.locator('[data-word='+id+']').tap();await t.locator('[data-slot="'+i+'"]').tap()}assert.match(await t.locator('[data-slot="2"]').textContent(),/자라요/);await t.locator('[data-letter=compose]').tap();await t.locator('[data-letter=next]').waitFor();await touch.close()}
assert.deepEqual(errors,[]);console.log('PASS: Lv19 boundary, world/NPC discovery, clues, real drag/touch/keyboard, hints, duplicate/lost/error responses, replay/reload/XP correction, per-owner reset, notebook/NPC memory, unchanged rewards and 1366/390/320 layout');
}finally{await browser.close();server.closeAllConnections();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
