const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');const {chromium}=require('playwright');const {server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,channel:'msedge'}),base='http://127.0.0.1:'+server.address().port;
 try{const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto(base);let f=page.frames().find(f=>f.url().includes('app-core.html'));const ready=async()=>f.waitForFunction(()=>document.getElementById('saProfileTitle')?.textContent.includes('별나래'));await ready();
 const xp=async n=>f.evaluate(async n=>{mockRpg.student.xp=n;await loadDashboard()},n),launch=async()=>{await f.evaluate(()=>openAdventureMap());await f.locator('[data-workshop=kindness-chapter]').waitFor({state:'attached'});if(await f.locator('[data-map-tab=notebook]').isVisible())await f.locator('[data-map-tab=notebook]').click();await f.locator('[data-workshop=kindness-chapter]').click()},choose=async id=>{await f.locator('[data-kind-choice="'+id+'"]').click();await f.locator('[data-kind-save]').click();await f.locator('[data-kind-next]').waitFor()};
 await xp(1249);await launch();assert.match(await f.locator('#saDialogSubtitle').textContent(),/Lv. 15/);assert.equal(await f.locator('[data-kind-choice]').count(),0);await f.locator('#studentAdventureDialog [data-sa=close]').click();await xp(1250);
 await f.evaluate(()=>enterHubScene('classroom'));await f.locator('[data-place=quests]').click();await f.locator('[data-npc-action=kindness]').click();assert.match(await f.locator('#saDialogTitle').textContent(),/나루/);await f.locator('[data-kind-save]').click();assert.match(await f.locator('#kindnessFeedback').textContent(),/먼저/);assert.equal(await f.evaluate(()=>mockRpg.kindnessSaves||0),0);
 await f.locator('[data-kind-choice=ask]').focus();await page.keyboard.press('Enter');await f.evaluate(()=>mockRpg.failKindness=true);await f.locator('[data-kind-save]').click();await f.waitForFunction(()=>document.getElementById('kindnessFeedback')?.textContent.includes('연결'));assert.equal(await f.locator('[data-kind-choice=ask]').getAttribute('aria-pressed'),'true');
 await f.evaluate(()=>{mockRpg.failKindness=false;mockRpg.dropKindnessReply=true});await f.locator('[data-kind-save]').click();await f.waitForFunction(()=>document.getElementById('kindnessFeedback')?.textContent.includes('연결'));assert.equal(await f.evaluate(()=>mockRpg.kindness.phase),1);
 await f.evaluate(()=>mockRpg.kindnessDelay=350);const saves=await f.evaluate(()=>mockRpg.kindnessSaves);await f.locator('[data-kind-save]').evaluate(b=>{b.click();b.click()});await page.keyboard.press('Escape');assert(await f.locator('#studentAdventureDialog').isVisible());await f.locator('[data-kind-next]').waitFor();assert.equal(await f.evaluate(()=>mockRpg.kindnessSaves),saves+1);await f.locator('[data-kind-next]').click();assert.match(await f.locator('.kindness-scene').textContent(),/먼저 물어봐/);
 await f.locator('[data-kind-choice=shop]').click();await f.locator('[data-kind-save]').click();await f.waitForFunction(()=>document.getElementById('kindnessFeedback')?.textContent.includes('파란'));assert.equal(await f.evaluate(()=>mockRpg.kindness.phase),1);
 fs.mkdirSync(shots,{recursive:true});for(const [width,height] of [[1366,768],[390,844],[320,640]]){await page.setViewportSize({width,height});assert.equal(await f.locator('#studentAdventureDialog').evaluate(el=>el.scrollWidth>el.clientWidth+1),false);for(const b of await f.locator('.kindness-choice').all()){const box=await b.boundingBox();assert(box.width>=44&&box.height>=44)}await page.screenshot({path:path.join(shots,'kindness-route-'+width+'.png'),fullPage:true});await f.locator('[data-kind-choice=library]').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(shots,'kindness-doors-'+width+'.png'),fullPage:true})}
 await choose('library');await f.locator('[data-kind-next]').click();await f.locator('#studentAdventureDialog [data-sa=close]').click();await page.reload();f=page.frames().find(f=>f.url().includes('app-core.html'));await ready();await xp(0);await launch();assert.match(await f.locator('#saDialogSubtitle').textContent(),/3 \/ 4/);await choose('introduce');await f.locator('[data-kind-next]').click();assert.match(await f.locator('.kindness-scene').textContent(),/토리/);await choose('leaf');await f.locator('[data-kind-next]').click();assert(await f.locator('.kindness-finish').isVisible());assert.equal(await f.locator('.kindness-profile').count(),1);assert.match(await f.locator('.kindness-memory').textContent(),/물었어요.*표지판.*소개했어요/s);
 await f.locator('[data-kind-pin=star]').click();await f.waitForFunction(()=>document.querySelector('[data-kind-pin=star]')?.getAttribute('aria-pressed')==='true');assert.match(await f.locator('.kindness-profile').textContent(),/별빛/);await f.locator('[data-kind-wear=false]').click();await f.waitForFunction(()=>!document.querySelector('.kindness-profile'));await f.locator('[data-kind-wear=true]').click();await f.waitForFunction(()=>document.querySelector('.kindness-profile'));assert.deepEqual(await f.evaluate(()=>[mockRpg.student.xp,mockRpg.student.gold,mockRpg.exploration.length]),[0,180,0]);
 await page.screenshot({path:path.join(shots,'kindness-finish-320.png'),fullPage:true});await f.locator('#studentAdventureDialog [data-sa=close]').click();await page.reload();f=page.frames().find(f=>f.url().includes('app-core.html'));await ready();await f.locator('.kindness-profile').click();assert(await f.locator('.kindness-finish').isVisible());assert.equal(await f.evaluate(()=>mockRpg.kindness.choices.length),4);
 await f.evaluate(()=>mockRpg.student.id=988);await f.locator('[data-kind-pin=sun]').click();assert.equal(await f.locator('[data-kind-pin]').count(),0);assert.match(await f.locator('#saDialogTitle').textContent(),/새 계정/);
 const touch=await browser.newPage({viewport:{width:320,height:640},hasTouch:true,isMobile:true});await touch.route('https://**',r=>r.abort());await touch.goto(base);const tf=touch.frames().find(f=>f.url().includes('app-core.html'));await tf.waitForFunction(()=>document.getElementById('saProfileTitle')?.textContent.includes('별나래'));await tf.evaluate(async()=>{mockRpg.student.xp=1250;await loadDashboard();await openAdventureMap()});await tf.locator('[data-workshop=kindness-chapter]').waitFor({state:'attached'});if(await tf.locator('[data-map-tab=notebook]').isVisible())await tf.locator('[data-map-tab=notebook]').click();await tf.locator('[data-workshop=kindness-chapter]').tap();await tf.locator('[data-kind-choice=listen]').tap();await tf.locator('[data-kind-save]').tap();await tf.locator('[data-kind-next]').waitFor();await tf.locator('[data-kind-next]').tap();assert.match(await tf.locator('.kindness-scene').textContent(),/천천히 들어/);await tf.locator('[data-kind-choice=library]').tap();await tf.locator('[data-kind-save]').tap();await tf.locator('[data-kind-next]').waitFor();await tf.locator('[data-kind-next]').tap();await tf.locator('[data-kind-choice=walk]').tap();await tf.locator('[data-kind-save]').tap();await tf.locator('[data-kind-next]').waitFor();await tf.locator('[data-kind-next]').tap();assert.match(await tf.locator('.kindness-scene').textContent(),/천천히 걸어/);await touch.close();
 assert.deepEqual(errors,[]);console.log('PASS: Lv15/NPC entry, two story branches, keyboard/touch, wrong route, recovery/replay/double click, save guard, reload/XP correction, pin editing/hide/profile, account change, economy and 1366/390/320 layouts');
 }finally{await browser.close();server.closeAllConnections();server.close()}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
