const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const {chromium}=require('playwright'),{server,shots}=require('./student-fixture.cjs');
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const page=await browser.newPage({viewport:{width:1366,height:768},hasTouch:true}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://**',r=>r.abort());await page.goto('http://127.0.0.1:'+server.address().port);const f=page.frames().find(x=>x.url().includes('app-core.html'));await f.waitForFunction(()=>window.studentCampus&&document.getElementById('saProfileTitle')?.textContent.includes('별나래'));await f.evaluate(()=>document.fonts.ready);fs.mkdirSync(shots,{recursive:true});
 await f.evaluate(async()=>{mockRpg.student.xp=3155;await loadDashboard()});
 const shot=name=>page.screenshot({path:path.join(shots,'game-ui-'+name+'.png'),fullPage:true});
 const geometry=async id=>f.locator(id).evaluate(el=>{const r=el.getBoundingClientRect();return{top:r.top,bottom:r.bottom,h:r.height,screen:innerHeight,overflow:el.scrollWidth>el.clientWidth+1,scroll:el.scrollHeight>el.clientHeight+1}});
 for(const [w,h] of [[1366,768],[390,844],[320,640]]){
  await page.setViewportSize({width:w,height:h});await f.evaluate(()=>enterHubScene('library'));await f.locator('.campus-scene-status').waitFor({state:'hidden'});await f.locator('[data-place=tori]').tap();await shot('tori-'+w);
  const talk=await geometry('#campusGuide');assert(!talk.overflow);assert(!talk.scroll,'Conversation should fit without a long menu scroll '+JSON.stringify(talk));assert(talk.bottom<=talk.screen+1);assert(talk.top>60,'Some world remains visible');
  assert.equal(await f.locator('.campus-guide-choices button').count(),4);for(const b of await f.locator('#campusGuide button:visible').all()){const r=await b.boundingBox();assert(r.width>=44&&r.height>=44)}
  const still=await f.locator('#hubPlayer').getAttribute('style');await page.keyboard.press('ArrowRight');assert.equal(await f.locator('#hubPlayer').getAttribute('style'),still);await f.locator('[data-guide=close]').first().tap();
  await f.evaluate(()=>enterHubScene('classroom'));await f.locator('[data-place=quests]').tap();await shot('teacher-'+w);const teacher=await geometry('#campusNpcDialog');assert(!teacher.overflow);assert(!teacher.scroll,'Teacher fits '+JSON.stringify(teacher));assert(teacher.top>30);await page.keyboard.press('Escape');
  await f.evaluate(()=>studentAdventure.map());await f.locator('#studentAdventureDialog[data-view=map]').waitFor();await shot('map-'+w);const map=await geometry('#studentAdventureDialog');assert(!map.overflow);assert(!map.scroll,'Map needs no webpage scrolling '+JSON.stringify(map));
  assert.equal(await f.locator('.sa-map-pin').count(),7);assert.equal(await f.locator('.sa-map-pin[aria-current=location]').getAttribute('data-chapter'),'classroom');assert(!await f.locator('.sa-workshop-links').isVisible());
  const overlap=await f.locator('.sa-map-pin').evaluateAll(es=>es.flatMap((a,i)=>es.slice(i+1).filter(b=>{const x=a.getBoundingClientRect(),y=b.getBoundingClientRect();return x.left<y.right&&x.right>y.left&&x.top<y.bottom&&x.bottom>y.top}).map(b=>a.dataset.chapter+'/'+b.dataset.chapter)));if(overlap.length)console.log(w,await f.locator('.sa-map-pin').evaluateAll(es=>es.map(e=>({id:e.dataset.chapter,width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height,minWidth:getComputedStyle(e).minWidth,left:e.getBoundingClientRect().left,top:e.getBoundingClientRect().top}))));assert.deepEqual(overlap,[],'Readable individual map markers');
  await f.locator('[data-map-tab=notebook]').tap();assert(await f.locator('.sa-workshop-links').isVisible());assert(!await f.locator('.sa-world').isVisible());await f.locator('#studentAdventureDialog').evaluate(el=>el.scrollTop=el.scrollHeight);assert(await f.locator('#studentAdventureDialog [data-sa=close]').evaluate(el=>el.getBoundingClientRect().top>=0));assert(await f.locator('[data-map-tab=world]').evaluate(el=>el.getBoundingClientRect().top>=0));await f.locator('[data-map-tab=world]').tap();assert(await f.locator('.sa-world').isVisible());await f.locator('[data-map-tab=notebook]').tap();await f.locator('[data-workshop=covers]').tap();assert.notEqual(await f.locator('#studentAdventureDialog').getAttribute('data-view'),'map');await page.keyboard.press('Escape');
  await f.evaluate(()=>studentAdventure.map());await f.locator('.sa-map-pin[data-chapter=library]').tap();assert.equal(await f.locator('#classroomHub').getAttribute('data-scene'),'library');
 }
 await f.evaluate(async()=>{mockRpg.student.xp=0;await loadDashboard();await studentAdventure.map(true)});await f.locator('.sa-map-pin[data-chapter=pond]').tap();assert.match(await f.locator('#saDialogBody').textContent(),/경험치/);assert.equal(await f.locator('.sa-world').count(),0);await page.keyboard.press('Escape');
 await page.emulateMedia({reducedMotion:'reduce'});await f.evaluate(()=>studentAdventure.map());assert.equal(await f.locator('.sa-pin-emblem').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await f.locator('[data-map-tab=notebook]').focus();await page.keyboard.press('Enter');assert(await f.locator('.sa-workshop-links').isVisible());await page.keyboard.press('Escape');
 assert.equal(await f.evaluate(()=>mockRpg.student.gold),180);assert.deepEqual(errors,[]);console.log('PASS: scenery-visible NPC speech/response balloons, Tori/teacher controls and no menu scroll at 1366/390/320, compact nonoverlapping map/current-place markers, separate retained notebook, locked locations, keyboard/touch, reduced motion and unchanged gold');
}finally{await browser.close();server.closeAllConnections();server.close()}})().catch(e=>{console.error(e);server.close();process.exitCode=1});
